PACKAGE=pingus
VERSION=0.5.0pre2-binary-i386
TMPDIR=$(PACKAGE)-$(VERSION)
TARNAME=$(PACKAGE)-$(VERSION).tar.bz2

all : dist

binary : src/Makefile.static src/pingus
	cd src/ && $(MAKE) -f Makefile.static
 
dist : binary
	mkdir -p $(TMPDIR)
	make install prefix=`pwd`/$(TMPDIR)
	cp src/pingus.static.comp $(TMPDIR)/games/pingus
	tar cjf $(TARNAME) $(TMPDIR)
	rm -rf $(TMPDIR)

