;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/desert5.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "PLE Level")
    (description "This level has no name ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (playable 1)
    (difficulty 75)
    (comment "floaters was 2, increased to 3, 'cause there doesn't seem to be a way to "
             "solve it cleanly with 2 floaters")
    (actions 
      (blocker 5)
      (bomber 20)
      (bridger 5)
      (climber 5)
      (floater 3))
    (music "none")
    (levelsize 1216 800))
  (objects 
    (surface-background 
      (surface 
        (image "textures/desert")
        (modifier "ROT0"))
      (color 0 0 0 1)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0))
    (hotspot 
      (surface 
        (image "entrances/wood_bottom")
        (modifier "ROT0"))
      (position 774 167 -100)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 699 539 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 699 311 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 699 657 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 295 658 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 699 420 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 404 658 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 255 748 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 827 702 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 272 708 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 725 536 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 849 624 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 849 378 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 676 431 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 448 709 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 624 658 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 676 311 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 676 565 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 570 701 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 399 690 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 676 406 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 643 658 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 676 595 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 923 550 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 756 333 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 923 274 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 794 399 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 662 750 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 685 709 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 676 501 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 713 437 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 676 342 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 702 423 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 660 738 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 663 779 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 655 701 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 688 646 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 676 385 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 698 746 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 679 761 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 674 717 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 693 549 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 702 490 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 295 497 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 963 113 0))
    (entrance 
      (position 827 206 0)
      (type "generic")
      (direction "left")
      (release-rate 50))
    (exit 
      (owner-id 0)
      (position 440 658 0)
      (surface 
        (image "exits/desert")
        (modifier "ROT0")))
    (hotspot 
      (surface 
        (image "entrances/wood_top")
        (modifier "ROT0"))
      (position 774 167 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
