;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/desert3.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Pass the pedestal")
    (description "After the Pingus successfully passed the large window room, they are entering "
                 "another great hall. A large pedestal is blocking the way to the entrance.")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 30)
    (number-to-save 30)
    (time 9000)
    (difficulty 70)
    (playable 1)
    (comment )
    (music "pingus-3.it")
    (actions 
      (basher 2)
      (blocker 10)
      (bridger 10)
      (climber 10)
      (digger 10)
      (floater 10)
      (jumper 10))
    (levelsize 1824 704))
  (objects 
    (surface-background 
      (surface 
        (image "textures/desert_room")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (hotspot 
      (surface 
        (image "entrances/wood_bottom")
        (modifier "ROT0"))
      (position 242 430 -100)
      (speed -1)
      (parallax 1))
    (entrance 
      (position 290 455 0)
      (type "generic")
      (direction "right")
      (release-rate 75)
      (owner-id 0))
    (hotspot 
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 1331 491 -50)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 901 227 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 1017 226 42))
    (exit 
      (owner-id 0)
      (position 1406 567 -47)
      (surface 
        (image "exits/desert")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/blobdune")
        (modifier "ROT0"))
      (position 903 550 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/blobdune")
        (modifier "ROT0"))
      (position 1036 555 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position -263 -33 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 37 -33 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 637 -16 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 337 -5 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 937 -37 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 198 549 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1237 -21 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 1064 405 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 850 405 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 954 405 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1537 -34 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1590 116 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 377 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/blobdune")
        (modifier "ROT0"))
      (position 1060 554 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 977 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1577 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1638 266 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position -75 116 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 965 201 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 912 201 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/blobdune")
        (modifier "ROT0"))
      (position 818 553 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position -16 266 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position -63 416 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position -223 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 77 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 677 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1277 566 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1781 416 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 1013 387 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 1481 417 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 937 387 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 633 471 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 652 310 42))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 861 387 42))
    (hotspot 
      (surface 
        (image "entrances/wood_top")
        (modifier "ROT0"))
      (position 242 431 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
