;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth5-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 15)
    (number-to-save 10)
    (time -1)
    (difficulty 70)
    (playable 1)
    (actions 
      (basher 5)
      (blocker 5)
      (bomber 2)
      (bridger 5)
      (slider 5))
    (music "none")
    (levelsize 1216 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/bwsortiebg")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -40 529 -100)
      (repeat 20)
      (speed 50))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 734 295 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 215 332 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 465 294 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/groundice")
        (modifier "ROT0"))
      (position 564 294 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/groundice")
        (modifier "ROT0"))
      (position 460 294 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 353 14 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 484 -17 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 833 -67 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 956 -68 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 744 -19 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 630 34 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 239 517 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 573 546 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 527 539 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 461 72 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 562 23 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 884 289 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 362 326 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 727 289 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 208 326 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 545 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 27 -16 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 368 -18 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 207 -37 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 697 116 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 720 93 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position -143 512 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 812 547 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 602 113 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 578 -38 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 184 41 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 104 2 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 330 131 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 616 25 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 151 59 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 286 517 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 294 124 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 183 60 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 633 179 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 964 -42 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 944 11 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 836 62 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 840 22 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 584 538 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 956 124 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 821 65 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 983 -6 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1103 65 0))
    (exit 
      (owner-id 0)
      (position 272 330 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (entrance 
      (position 899 226 0)
      (type "generic")
      (direction "left")
      (release-rate 150)
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/industrial_top")
        (modifier "ROT0"))
      (position 878 191 100)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -7 548 100)
      (repeat 20)
      (speed 50))))
;; EOF ;;
