;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth-23-rz+eriksoe.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Trifork")
    (description "There are three exits - and you have to use all of them.")
    (author "Rune Zedeler <rz@daimi.au.dk> and Erik Soe Sorensen <eriksoe@daimi.au.dk>")
    (number-of-pingus 50)
    (number-to-save 45)
    (time 9000)
    (difficulty 65)
    (playable 1)
    (comment )
    (music "none")
    (actions 
      (bridger 2)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (levelsize 1200 768))
  (objects 
    (surface-background 
      (surface 
        (image "textures/stones")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position -9 -38 -150))
    (exit 
      (owner-id 0)
      (position 907 663 -50)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock6")
        (modifier "ROT0"))
      (position 682 286 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock5")
        (modifier "ROT0"))
      (position 682 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock3")
        (modifier "ROT0"))
      (position 682 222 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock6")
        (modifier "ROT0"))
      (position 810 94 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock6")
        (modifier "ROT0"))
      (position 682 94 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock3")
        (modifier "ROT0"))
      (position 746 94 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock6")
        (modifier "ROT0"))
      (position 746 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock3")
        (modifier "ROT0"))
      (position 810 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock5")
        (modifier "ROT0"))
      (position 810 222 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock6")
        (modifier "ROT0"))
      (position 746 222 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock6")
        (modifier "ROT0"))
      (position 810 286 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock3")
        (modifier "ROT90FLIP"))
      (position 746 286 0))
    (exit 
      (owner-id 0)
      (position 940 351 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 293 350 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 861 92 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 723 92 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 801 130 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position -48 105 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos3")
        (modifier "ROT0"))
      (position 735 220 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos3")
        (modifier "ROT0"))
      (position 754 284 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0FLIP"))
      (position 827 221 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 676 157 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 538 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 646 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 37 97 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT90FLIP"))
      (position -84 -87 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 342 -8 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 810 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 722 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT90FLIP"))
      (position 207 -105 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT90FLIP"))
      (position 88 -73 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 409 -51 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 78 -82 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position -59 -28 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT90FLIP"))
      (position 30 -108 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 341 -47 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 391 76 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 403 13 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT90FLIP"))
      (position 537 -144 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 264 -56 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column")
        (modifier "ROT0"))
      (position 1066 83 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 266 60 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 162 68 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column")
        (modifier "ROT0"))
      (position 1136 75 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT90FLIP"))
      (position 141 13 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_flat")
        (modifier "ROT0"))
      (position 1121 208 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 379 90 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 152 103 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 200 95 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_vert")
        (modifier "ROT0"))
      (position 1041 129 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_horz")
        (modifier "ROT0"))
      (position 954 1 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_vert")
        (modifier "ROT0"))
      (position 1076 183 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_horz")
        (modifier "ROT0"))
      (position 766 -53 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 1062 -49 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column")
        (modifier "ROT0"))
      (position 12 569 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_up")
        (modifier "ROT0"))
      (position 15 445 0))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -28.8571 695.143 -50)
      (repeat 5)
      (speed 20))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 291.143 695.143 -50)
      (repeat 5)
      (speed 20))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 611.143 695.143 -50)
      (repeat 5)
      (speed 20))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 931.143 695.143 -50)
      (repeat 5)
      (speed 20))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/misc/spike")
        (modifier "ROT0"))
      (position 198 566 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar2")
        (modifier "ROT0"))
      (position 195 685 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/misc/spike")
        (modifier "ROT0FLIP"))
      (position 800 563 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar2")
        (modifier "ROT0"))
      (position 1031 683 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 269 712 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT90FLIP"))
      (position 312 657 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 157 701 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 234 659 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 399 673 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 907 667 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 515 664 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 664 641 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT90FLIP"))
      (position 754 645 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 793 656 0))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -8.8571 705.143 0)
      (repeat 5)
      (speed 20))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 311.143 705.143 0)
      (repeat 5)
      (speed 20))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 631.143 705.143 0)
      (repeat 5)
      (speed 20))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 951.143 705.143 0)
      (repeat 5)
      (speed 20))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 185 349 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 199 347 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 265 346 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 321 345 0))
    (entrance 
      (position 557 175 0)
      (type "generic")
      (direction "right")
      (release-rate 100)
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/industrial_top")
        (modifier "ROT0"))
      (position 536 111 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
