;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth19-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (jumper 20)
      (slider 20))
    (music "none")
    (levelsize 1216 600))
  (objects 
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 513.56 348.52 0))
    (surface-background 
      (surface 
        (image "textures/stones")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (exit 
      (owner-id 0)
      (position 594.56 210.52 -50)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 577 376 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 501 6.99997 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 186 25 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 65 71 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 347 5.99997 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 719 51 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 843 51 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 965 53 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 713 -41 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT90FLIP"))
      (position 790 -12 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT90FLIP"))
      (position 1000 -11 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT90FLIP"))
      (position 915 -4.00002 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 1136 -43 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 602 -100 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 1110 -36 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 297 -6 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT180"))
      (position 123 -23 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT180"))
      (position -36 -22 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 612 387 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 498.56 204.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 418 400 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 291 402 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 288 64 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 452 54 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 706 42 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 251.56 384.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 820 306 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 947 327 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 682 372 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 880 344 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 573 379 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 842 43 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 1061 71 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 775.56 285.52 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 856 433 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 588 551 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 332 591 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 858 486 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 859 543 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 846.56 285.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 391.56 384.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 638.56 204.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 655.56 348.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 915.56 285.52 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone4")
        (modifier "ROT0"))
      (position 265.56 282.52 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 321 416 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 847 311 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 456 -63 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 253 -129 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0FLIP"))
      (position 55 -27 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT180"))
      (position -136 108 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 241 12 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0FLIP"))
      (position 193 25 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position -55.0001 8.00001 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 518.56 349.52 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 531 -70 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/groundice")
        (modifier "ROT0"))
      (position 561 349 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_vert")
        (modifier "ROT0"))
      (position 605 215 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_vert")
        (modifier "ROT0"))
      (position 604 272 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 254.56 385.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 501.56 205.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 778.56 286.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 322.56 384.52 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 569.56 204.52 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 583 435 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 327 475 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 853 370 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 586 498 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece9")
        (modifier "ROT0"))
      (position 330 538 0))
    (hotspot 
      (surface 
        (image "hotspots/signposts/arrow_northwest")
        (modifier "ROT0"))
      (position 867 246 0)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/signposts/arrow_northeast")
        (modifier "ROT0"))
      (position 430.56 343.52 0)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "entrances/wood_bottom")
        (modifier "ROT0"))
      (position 339 216 -50)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "entrances/wood_top")
        (modifier "ROT0"))
      (position 339 216 50)
      (speed -1)
      (parallax 1))
    (entrance 
      (position 389 251 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))))
;; EOF ;;
