;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth17-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 45)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (actions 
      (blocker 5)
      (bridger 10)
      (digger 2)
      (floater 5))
    (music "none")
    (levelsize 1216 1216))
  (objects 
    (surface-background 
      (surface 
        (image "textures/rooftile2")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 28 180 -150))
    (exit 
      (owner-id 0)
      (position 726 337 -50)
      (surface 
        (image "exits/mud")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0FLIP"))
      (position 477 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 561 559 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 455 554 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 705 558 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 599 553 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 634 556 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 528 551 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 574 555 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 468 550 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 296 806 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 377 811 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe1")
        (modifier "ROT0"))
      (position 425 503 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe1")
        (modifier "ROT0"))
      (position 394 503 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 643 777 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 461 550 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 370 -20 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 287 -21 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 450 -23 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 454 370 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 294 607 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 308 363 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 290 734 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 301 497 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 453 497 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 499 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 469 775 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 304 773 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 783 775 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 610 333 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 360 324 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 170 -12 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 420 -22 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 299 100 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 240 322 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 452 472 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 334 472 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 391 136 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 395 338 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 754 332 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 504 323 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 683 330 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 433 321 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 623 329 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 373 320 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 311 321 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 246 320 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 331 594 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 336 350 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 487 616 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed1")
        (modifier "ROT0"))
      (position 511 440 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 487 513 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 355 735 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/weed2")
        (modifier "ROT0"))
      (position 360 491 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 955 618 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar1")
        (modifier "ROT0"))
      (position 818 619 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 829 591 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 905 591 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 924 781 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 853 779 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 793 778 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 874 606 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 874 591 0))
    (entrance 
      (position 422 205 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 427 409 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 902 779 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/industrial_top")
        (modifier "ROT0"))
      (position 401 171 100)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "entrances/industrial_top")
        (modifier "ROT0"))
      (position 405 373 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
