;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth6-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 40)
    (number-to-save 30)
    (time -1)
    (difficulty 50)
    (playable 1)
    (comment "description missing")
    (actions 
      (basher 5)
      (blocker 5)
      (bomber 5)
      (bridger 15)
      (digger 5)
      (jumper 5))
    (music "none")
    (levelsize 1608 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/rooftile2")
        (modifier "ROT0"))
      (color 0 0 0 0.5)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 65 11 -150))
    (spike 
      (position 1030 76 -100))
    (spike 
      (position 1032 136 -100))
    (spike 
      (position 1032 107 -100))
    (spike 
      (position 1034 167 -100))
    (spike 
      (position 1036 198 -100))
    (hotspot 
      (surface 
        (image "entrances/wood_bottom")
        (modifier "ROT0"))
      (position 246 88 -50)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -54 525 -50)
      (repeat 27)
      (speed 50))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 1085 262 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 837 261 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 575 261 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 312 260 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 1085 433 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 837 432 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 575 432 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 312 431 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 1087 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 839 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 577 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 314 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 1087 519 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 839 518 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 577 518 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 314 517 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 1012 224 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 764 223 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 502 223 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 239 222 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 1073 545 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 825 544 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 493 534 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 307 543 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 250 530 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 584 527 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 1016 518 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 768 517 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_right")
        (modifier "ROT0"))
      (position 1284.84 364.612 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_right")
        (modifier "ROT0"))
      (position 1279.73 253.388 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_right")
        (modifier "ROT0"))
      (position 1285 476 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_right")
        (modifier "ROT0"))
      (position 1285.84 420.612 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_right")
        (modifier "ROT0"))
      (position 1280.73 309.388 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_right")
        (modifier "ROT0"))
      (position 1283 533 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_left")
        (modifier "ROT0"))
      (position 1284.84 336.612 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_left")
        (modifier "ROT0"))
      (position 1281.73 225.388 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_left")
        (modifier "ROT0"))
      (position 1285 448 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_left")
        (modifier "ROT0"))
      (position 1285.84 392.612 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_left")
        (modifier "ROT0"))
      (position 1280.73 281.388 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/misc/bridge_left")
        (modifier "ROT0"))
      (position 1283 504 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/space/smalltower")
        (modifier "ROT0"))
      (position 1350 222 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/space/smalltower")
        (modifier "ROT0"))
      (position 1280 225 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/space/smalltower")
        (modifier "ROT0"))
      (position 1350 365 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/space/smalltower")
        (modifier "ROT0"))
      (position 1280 309 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/space/way")
        (modifier "ROT0"))
      (position 1252 558 0))
    (exit 
      (owner-id 0)
      (position 1140 229 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (entrance 
      (position 296 117 0)
      (type "generic")
      (direction "right")
      (release-rate 150)
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/wood_top")
        (modifier "ROT0"))
      (position 246 88 100)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -21 545 100)
      (repeat 26)
      (speed 50))))
;; EOF ;;
