;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth21-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 30)
    (number-to-save 20)
    (time -1)
    (difficulty 40)
    (playable 1)
    (comment )
    (actions 
      (bomber 10)
      (bridger 1))
    (music "none")
    (levelsize 1216 600))
  (objects 
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 559 216 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 914 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 850 278 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 850 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 914 278 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 786 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 722 278 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 722 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 786 278 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 786 214 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 722 214 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 914 214 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 850 214 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 556 341 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 492 277 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 492 341 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 556 277 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 428 341 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 364 277 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 364 341 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 428 277 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 428 213 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 364 213 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 556 213 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock2")
        (modifier "ROT0"))
      (position 492 213 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 750 523 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 510 521 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 749 436 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone6")
        (modifier "ROT0"))
      (position 508 434 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 550 390 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 544 435 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 676 428 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 434 428 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 313 390 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 794 390 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 666 389 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 430 391 0))
    (exit 
      (owner-id 0)
      (position 667 396 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (entrance 
      (position 660 146 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 636 215 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 684 214 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 587 213 0))
    (surface-background 
      (surface 
        (image "textures/bwsortiebg")
        (modifier "ROT0"))
      (color 0 0 0 0.4)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.3)
      (para-y 0.3)
      (stretch-x 0)
      (stretch-y 0)
      (position -131 -24 -150))
    (surface-background 
      (surface 
        (image "textures/green_tendrils")
        (modifier "ROT0"))
      (color 0 0 0 0.4)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position -131 -24 -150))))
;; EOF ;;
