;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth10-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 30)
    (number-to-save 20)
    (time -1)
    (difficulty 40)
    (playable 1)
    (comment )
    (actions 
      (bomber 10)
      (blocker 5)
      (bridger 4)
      (miner 4))
    (music "none")
    (levelsize 1216 1216))
  (objects 
    (surface-background 
      (surface 
        (image "textures/rock6")
        (modifier "ROT0"))
      (color 0.5 0 0 0.2)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position -25 -18 -150))
    (hotspot 
      (surface 
        (image "entrances/wood_bottom")
        (modifier "ROT0"))
      (position 479 88 -50)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position -91 1137 -50)
      (repeat 22)
      (speed 50))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 483 1013 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone2")
        (modifier "ROT0"))
      (position 382 993 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone2")
        (modifier "ROT0"))
      (position 261 985 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone2")
        (modifier "ROT0"))
      (position 939 966 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone2")
        (modifier "ROT0"))
      (position 554 984 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 634 974 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 413 1127 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 593 1033 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 822 1000 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 740 1048 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 830 1098 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 656 1106 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 413 1026 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 290 1034 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 720 952 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 296 958 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone1")
        (modifier "ROT0"))
      (position 410 951 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone4")
        (modifier "ROT0"))
      (position 778 843 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 609 487 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 595 756 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 321 631 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 544 470 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 530 739 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 256 614 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 665 468 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 651 737 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 377 614 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 361 843 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 311 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 360 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 472 215 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone5")
        (modifier "ROT0"))
      (position 800 1166 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone5")
        (modifier "ROT0"))
      (position 653 1160 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone5")
        (modifier "ROT0"))
      (position 529 1156 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone5")
        (modifier "ROT0"))
      (position 784 948 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone5")
        (modifier "ROT0"))
      (position 471 963 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 326 1085 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 980 1124 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 496 843 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 495 346 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 607 215 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 801 468 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 787 737 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 512 612 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 431 843 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 430 346 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 542 215 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 736 468 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 722 737 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 447 612 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 369 844 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 321 345 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 368 347 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 480 216 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 677 468 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 663 737 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 388 612 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 616 469 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 602 738 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 327 613 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 938 960 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 897 953 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 843 947 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 782 948 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 673 969 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 613 967 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 551 963 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 320 959 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 386 959 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 501 958 0))
    (exit 
      (owner-id 0)
      (position 706 977 -5)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 444 952 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 552 469 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 538 738 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 263 613 0))
    (entrance 
      (position 530 116 0)
      (type "generic")
      (direction "right")
      (release-rate 50)
      (owner-id 0))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position -46 1155 50)
      (repeat 22)
      (speed 50))
    (hotspot 
      (surface 
        (image "entrances/wood_top")
        (modifier "ROT0"))
      (position 479 88 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
