;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth1-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time 9000)
    (difficulty 5)
    (playable 0)
    (comment )
    (actions 
      (bomber 5)
      (bridger 10)
      (floater 5)
      (digger 1)
      (blocker 20))
    (music "none")
    (levelsize 1920 928))
  (objects 
    (surface-background 
      (surface 
        (image "textures/cyanspace")
        (modifier "ROT0"))
      (color 0 0 0 0.1)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.1)
      (para-y 0.1)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 1369 368 -60)
      (repeat 6)
      (speed 50))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 712 854 -60)
      (repeat 14)
      (speed 50))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 730 866 -60)
      (repeat 14)
      (speed 50))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 1065 292 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 828 295 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 197 473 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/jungle/carabatreesmall")
        (modifier "ROT0"))
      (position 708 140 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 800 333 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 750 443 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 691 333 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 650 409 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 748 295 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1163 290 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1127 304 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 940 284 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1295 524 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1142 399 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1101.22 320.195 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 599 376 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 539 501 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 643 506 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 907 364 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 911 315 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/jungle/carabatreesmall")
        (modifier "ROT0"))
      (position 189 326 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1005 328 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 607 842 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 594 760 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 1559 802 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 401 811 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1681 803 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 453 779 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 456 695 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 513 599 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1142 366 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1401 461 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1223.72 292.283 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1295 415 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1230 423 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1082 298 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 1417 444 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 485 590 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 463 816 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 550 680 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 791 456 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 1502 459 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 950 378 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 234 502 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 185 504 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_left")
        (modifier "ROT0"))
      (position 786 770 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_left")
        (modifier "ROT0"))
      (position 1489 329 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_left")
        (modifier "ROT0"))
      (position 1420 329 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_left")
        (modifier "ROT0"))
      (position 1060 610 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_left")
        (modifier "ROT0"))
      (position 975 769 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_left")
        (modifier "ROT0"))
      (position 1184 710 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_right")
        (modifier "ROT0"))
      (position 867 770 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_right")
        (modifier "ROT0"))
      (position 1570 329 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_right")
        (modifier "ROT0"))
      (position 1501 329 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_right")
        (modifier "ROT0"))
      (position 1141 610 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_right")
        (modifier "ROT0"))
      (position 1171 768 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform_right")
        (modifier "ROT0"))
      (position 1380 709 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform")
        (modifier "ROT0"))
      (position 1055 765 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform")
        (modifier "ROT0"))
      (position 1264 706 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/well")
        (modifier "ROT0"))
      (position 328 477 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1664 326 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1728 233 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1664 233 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1728 326 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1438 428 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1354 405 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1354 374 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1760 295 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1710 233 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1710 326 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1760 265 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 1556 428 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 246 499 0))
    (entrance 
      (position 0 0 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 925 210 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 1723 326 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (switchdoor 
      (switch 
        (position 822 732 0))
      (door 
        (height 15)
        (position 1668 265 0)))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1374 428 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1534 428 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1470 428 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1566 429 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1630 429 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/rectsolid")
        (modifier "ROT0"))
      (position 1662 429 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1726 429 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1748 377 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/crystal/smallsolid")
        (modifier "ROT0"))
      (position 1748 408 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 670 570 0))))
;; EOF ;;
