;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/hellmouth9-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 49)
    (time -1)
    (difficulty 80)
    (playable 1)
    (comment "playable, but description missing ")
    (actions 
      (basher 3)
      (blocker 1)
      (bomber 1)
      (bridger 7)
      (climber 5)
      (digger 2)
      (miner 1)
      (slider 1))
    (music "none")
    (levelsize 1408 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/rooftile2")
        (modifier "ROT0"))
      (color 0 0 0 0.4)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 39 -63 -150))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -57 530 -50)
      (repeat 24)
      (speed 50))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe1")
        (modifier "ROT0"))
      (position 443.956 340.411 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe1")
        (modifier "ROT0"))
      (position 418.464 340.064 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe2")
        (modifier "ROT0"))
      (position 367.551 244.56 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe2")
        (modifier "ROT0"))
      (position 367.881 333.035 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe2")
        (modifier "ROT0"))
      (position 367.898 276.837 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe2")
        (modifier "ROT0"))
      (position 367.169 365.776 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe2")
        (modifier "ROT0"))
      (position 367.551 301.56 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/industrial/pipe1")
        (modifier "ROT0"))
      (position 386.411 340.446 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 711 230 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 889.814 222.636 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 767 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 710 288 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 645 362 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone3")
        (modifier "ROT0"))
      (position 383 414 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 458.117 313.551 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 472 395 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 1075.05 217.805 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 787.279 226.528 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 369.052 225.805 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 424 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 462 223 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 717 220 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 194.239 393.644 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 342.239 395.644 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone2")
        (modifier "ROT0"))
      (position 120 376 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone2")
        (modifier "ROT0"))
      (position 158 260 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/groundice")
        (modifier "ROT0"))
      (position 438.796 395 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 444.032 281.907 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 421.032 246.907 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 477.735 259.729 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 302 431 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 251 437 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 831.475 285.991 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 744 343 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 183 394 0))
    (entrance 
      (position 635 305 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 1204 221 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/industrial_top")
        (modifier "ROT0"))
      (position 615 268 100)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -19 546 100)
      (repeat 24)
      (speed 50))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/flower")
        (modifier "ROT0"))
      (position 502 195 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 616 393 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 1220 215 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 1176 219 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 1114 216 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 1079 218 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 953 229 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 926 223 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 867 221 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 821 221 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 764 218 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 723 222 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 365 225 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 421 222 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 478 220 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 543 225 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 605 225 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 258 393 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 313 393 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 371 393 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 663 389 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 561 393 0))))
;; EOF ;;
