;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/playable/indiana-yingwan.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Pingus Jones and (not really ;) the Last Exit")
    (description "Dr. Jones' notebook: (1) the breath of God: only the penitent pingus will "
                 "pass; (2) the word of God... in reverse; (3) the path of God: leap from the "
                 "head of something like a cat.")
    (author "Ying-Wan Lam <yingwan.lam@yale.edu>")
    (number-of-pingus 50)
    (number-to-save 40)
    (time 9000)
    (playable 1)
    (actions 
      (basher 5)
      (blocker 10)
      (bomber 10)
      (bridger 15)
      (digger 5)
      (jumper 50)
      (miner 5))
    (music "none")
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/desert_room")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0))
    (hotspot 
      (surface 
        (image "hotspots/desert/bigdimwall")
        (modifier "ROT0"))
      (position 906 155 -10)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/bigdimwall")
        (modifier "ROT0"))
      (position 907 304 -10)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/bigdimwall")
        (modifier "ROT0"))
      (position 906 453 -10)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/smallsphinx")
        (modifier "ROT0"))
      (position 836 26 -5)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position -10 535 -5)
      (repeat 14)
      (speed 50))
    (groundpiece 
      (type "ground")
      (surface 
        (image "hotspots/desert/smalldimwall")
        (modifier "ROT0"))
      (position 1074 435 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "hotspots/desert/smalldimwall")
        (modifier "ROT0"))
      (position 1150 435 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "hotspots/desert/smalldimwall")
        (modifier "ROT0"))
      (position 1132 304 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/mediumsand")
        (modifier "ROT0"))
      (position 507 373 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/mediumsand")
        (modifier "ROT0"))
      (position 358 373 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/mediumsand")
        (modifier "ROT0"))
      (position -49 298 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/mediumsand")
        (modifier "ROT0"))
      (position -85 373 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/mediumsand")
        (modifier "ROT0"))
      (position 62 373 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/mediumsand")
        (modifier "ROT0"))
      (position 210 373 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallsand")
        (modifier "ROT0"))
      (position 1125 565 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallsand")
        (modifier "ROT0"))
      (position 101 336 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 283 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 347 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 475 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 411 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 219 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 155 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 539 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 475 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 411 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 347 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 283 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 219 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1194 155 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallsand")
        (modifier "ROT0"))
      (position 903 566 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 848 539 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallsand")
        (modifier "ROT0"))
      (position 1051 566 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallsand")
        (modifier "ROT0"))
      (position 977 566 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/leftsmallsand")
        (modifier "ROT0"))
      (position 101 299 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/leftsmallsand")
        (modifier "ROT0"))
      (position 176 336 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 240 231 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 316 193 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 835 71 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 772 155 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 620 155 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 469 155 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 393 155 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/rightsmallbrick")
        (modifier "ROT0"))
      (position 164 231 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/rightsmallbrick")
        (modifier "ROT0"))
      (position 240 193 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/desert/rightsmallbrick")
        (modifier "ROT0"))
      (position 317 155 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallsand")
        (modifier "ROT0"))
      (position -8 261 0))
    (entrance 
      (position 595 306 0)
      (type "generic")
      (direction "right")
      (release-rate 50)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 987 566 0)
      (surface 
        (image "exits/desert")
        (modifier "ROT0"))
      (owner-id 0))
    (hotspot 
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 544 155 0)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 696 155 0)
      (speed -1)
      (parallax 1))
    (hammer 
      (position 392 195 0))
    (hotspot 
      (surface 
        (image "hotspots/desert/smallD")
        (modifier "ROT0"))
      (position 567 156 5)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/smallE")
        (modifier "ROT0"))
      (position 718 157 5)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/smallD")
        (modifier "ROT0"))
      (position 416 155 5)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/smallO")
        (modifier "ROT0"))
      (position 490 157 5)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/desert/smallG")
        (modifier "ROT0"))
      (position 638 157 5)
      (speed -1)
      (parallax 1))))
;; EOF ;;
