;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/wip/am_nil-luki.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "PLE Level")
    (description "This level has no name ")
    (author )
    (number-of-pingus 100)
    (number-to-save 50)
    (time 9000)
    (difficulty 5)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/default")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/ground/desert/pillar2")
        (modifier "ROT0"))
      (position 307 457 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/ground/desert/pillar2")
        (modifier "ROT0"))
      (position 150 457 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 323 420 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 248 420 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 172 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 96 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 20 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 25 582 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position -44 581 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 299 577 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 156 578 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "liquids/swater")
        (modifier "ROT0"))
      (position 712 560 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "liquids/swater")
        (modifier "ROT0"))
      (position 649 561 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "liquids/swater")
        (modifier "ROT0"))
      (position 585 561 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "liquids/swater")
        (modifier "ROT0"))
      (position 521 561 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "liquids/swater")
        (modifier "ROT0"))
      (position 458 561 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 754 575 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 877 576 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 1005 578 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/sluggydu")
        (modifier "ROT0"))
      (position 1072 578 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/ground/misc/green2")
        (modifier "ROT0"))
      (position 647 390 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/ground/misc/green1")
        (modifier "ROT0"))
      (position 461 409 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/smallbrickpiece")
        (modifier "ROT0"))
      (position 564 581 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/platform")
        (modifier "ROT0"))
      (position 397 415 0))
    (entrance 
      (position 71 502 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 95 421 0)
      (surface 
        (image "exits/desert")
        (modifier "ROT0"))
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/wood_bottom")
        (modifier "ROT0"))
      (position 28 455 0)
      (speed -1)
      (parallax 1))))
;; EOF ;;
