;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/wip/hotmush-gordon.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Hot Mush")
    (description "Get past the lava and enjoy the toasted mushrooms. But be quick, find the "
                 "exit before the ice melts. ")
    (author "Ashleigh Gordon")
    (number-of-pingus 40)
    (number-to-save 20)
    (time 5000)
    (difficulty 5)
    (playable 0)
    (comment )
    (actions 
      (basher 10)
      (blocker 10)
      (bomber 0)
      (bridger 20)
      (climber 0)
      (digger 10)
      (floater 0)
      (jumper 20)
      (miner 60))
    (music "none")
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/anim_fire")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 278 538 -100)
      (repeat 5)
      (speed 50))
    (laser_exit 
      (position 724 278 -100))
    (laser_exit 
      (position 688 17 -100))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece1")
        (modifier "ROT0"))
      (position 38 141 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece1")
        (modifier "ROT0"))
      (position 135 191 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece1")
        (modifier "ROT0"))
      (position 478 485 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 685 337 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 737 336 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 750 237 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 705 239 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 652 237 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 595 238 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 700 76 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 163 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 244 241 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 298 241 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 352 241 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 118 424 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 113 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 74 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece3")
        (modifier "ROT0"))
      (position 382 237 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 272 272 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 271 304 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 240 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 209 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 178 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 147 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 115 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 84 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 55 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 25 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 84 537 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 22 537 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 196 539 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 145 538 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 564 540 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 616 538 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 738 537 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/mushroom/toadstool3")
        (modifier "ROT0"))
      (position 250 433 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar3")
        (modifier "ROT0"))
      (position 262 95 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/mushroom/toadstool4")
        (modifier "ROT0"))
      (position 589 405 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/slopedr")
        (modifier "ROT0"))
      (position 593 338 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/slopedr")
        (modifier "ROT0"))
      (position 425 78 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/slopedr")
        (modifier "ROT0"))
      (position 597 76 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/slopedr")
        (modifier "ROT0"))
      (position 522 120 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/slopedr")
        (modifier "ROT0"))
      (position 325 130 0))
    (entrance 
      (position 150 89 0)
      (type "cloud")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 154 419 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (guillotine 
      (position 425 147 0))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 23 539 100)
      (repeat 5)
      (speed 50))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 529 538 100)
      (repeat 5)
      (speed 50))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 0 243 100)
      (repeat 5)
      (speed 50))
    (liquid 
      (surface 
        (image "liquids/lava")
        (modifier "ROT0"))
      (position 10 599 100)
      (repeat 13)
      (speed 50))))
;; EOF ;;
