.TH PINGUS 6 
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
Pingus \- A free Lemmings(TM) clone
.SH SYNOPSIS
.B pingus
.I "[options...] [levelfile]"
.SH "DESCRIPTION"
Pingus is a free Lemmings clone covered under the GPL. 

.SH "OPTIONS"
For a list of available options use:

.B % pingus --help

.SH "SEE ALSO"
/usr/share/doc/pingus

http://pingus.seul.org

.SH AUTHOR
This manual page was written by Ingo Ruhnke <grumbel@gmx.de>
