// Automatic generated by gen-scrfile.scm - don't edit by hand!

section misc
{
        column1 = ../images/groundpieces/remove/misc/column1.png (type=surface);
        dia1 = ../images/groundpieces/remove/misc/dia1.png (type=surface);
        rect1 = ../images/groundpieces/remove/misc/rect1.png (type=surface);
        rect2 = ../images/groundpieces/remove/misc/rect2.png (type=surface);
}

// EOF //
