// Automatic generated by gen-scrfile.scm - don't edit by hand!

section crystal
{
        block = ../images/groundpieces/ground/crystal/block.png (type=surface);
        column = ../images/groundpieces/ground/crystal/column.png (type=surface);
        diagcrystal = ../images/groundpieces/ground/crystal/diagcrystal.png (type=surface);
        hexcrystal = ../images/groundpieces/ground/crystal/hexcrystal.png (type=surface);
        horiz = ../images/groundpieces/ground/crystal/horiz.png (type=surface);
        horiz2 = ../images/groundpieces/ground/crystal/horiz2.png (type=surface);
        pipe = ../images/groundpieces/ground/crystal/pipe.png (type=surface);
        pipeend = ../images/groundpieces/ground/crystal/pipeend.png (type=surface);
        platform = ../images/groundpieces/ground/crystal/platform.png (type=surface);
        platform2 = ../images/groundpieces/ground/crystal/platform2.png (type=surface);
        pointleft = ../images/groundpieces/ground/crystal/pointleft.png (type=surface);
        pointright = ../images/groundpieces/ground/crystal/pointright.png (type=surface);
        skinnycrystal = ../images/groundpieces/ground/crystal/skinnycrystal.png (type=surface);
        smcrystal = ../images/groundpieces/ground/crystal/smcrystal.png (type=surface);
        tesselate = ../images/groundpieces/ground/crystal/tesselate.png (type=surface);
}

section desert
{
        bigblock-broken1 = ../images/groundpieces/ground/desert/bigblock-broken1.png (type=surface);
        bigblock-broken2 = ../images/groundpieces/ground/desert/bigblock-broken2.png (type=surface);
        bigblock-broken3 = ../images/groundpieces/ground/desert/bigblock-broken3.png (type=surface);
        bigdune1 = ../images/groundpieces/ground/desert/bigdune1.png (type=surface);
        bigprickpiece = ../images/groundpieces/ground/desert/bigprickpiece.png (type=surface);
        bigsand = ../images/groundpieces/ground/desert/bigsand.png (type=surface);
        blobdune = ../images/groundpieces/ground/desert/blobdune.png (type=surface);
        column = ../images/groundpieces/ground/desert/column.png (type=surface);
        column_piece1 = ../images/groundpieces/ground/desert/column_piece1.png (type=surface);
        column_piece2 = ../images/groundpieces/ground/desert/column_piece2.png (type=surface);
        column_piece3 = ../images/groundpieces/ground/desert/column_piece3.png (type=surface);
        domedune = ../images/groundpieces/ground/desert/domedune.png (type=surface);
        flat = ../images/groundpieces/ground/desert/flat.png (type=surface);
        flatdune = ../images/groundpieces/ground/desert/flatdune.png (type=surface);
        leftsmallbrick = ../images/groundpieces/ground/desert/leftsmallbrick.png (type=surface);
        leftsmallsand = ../images/groundpieces/ground/desert/leftsmallsand.png (type=surface);
        mediumsand = ../images/groundpieces/ground/desert/mediumsand.png (type=surface);
        middleprickpiece = ../images/groundpieces/ground/desert/middleprickpiece.png (type=surface);
        peakdune = ../images/groundpieces/ground/desert/peakdune.png (type=surface);
        pillar1 = ../images/groundpieces/ground/desert/pillar1.png (type=surface);
        pillar2 = ../images/groundpieces/ground/desert/pillar2.png (type=surface);
        pillar3 = ../images/groundpieces/ground/desert/pillar3.png (type=surface);
        platform = ../images/groundpieces/ground/desert/platform.png (type=surface);
        platform_left = ../images/groundpieces/ground/desert/platform_left.png (type=surface);
        platform_right = ../images/groundpieces/ground/desert/platform_right.png (type=surface);
        rightsmallbrick = ../images/groundpieces/ground/desert/rightsmallbrick.png (type=surface);
        rightsmallsand = ../images/groundpieces/ground/desert/rightsmallsand.png (type=surface);
        sluggydu = ../images/groundpieces/ground/desert/sluggydu.png (type=surface);
        smallbrickpiece = ../images/groundpieces/ground/desert/smallbrickpiece.png (type=surface);
        smallsand = ../images/groundpieces/ground/desert/smallsand.png (type=surface);
}

section foliage
{
        flax1 = ../images/groundpieces/ground/foliage/flax1.png (type=surface);
        flax2 = ../images/groundpieces/ground/foliage/flax2.png (type=surface);
        midtree1 = ../images/groundpieces/ground/foliage/midtree1.png (type=surface);
        midtree2 = ../images/groundpieces/ground/foliage/midtree2.png (type=surface);
        oak1 = ../images/groundpieces/ground/foliage/oak1.png (type=surface);
        rock1 = ../images/groundpieces/ground/foliage/rock1.png (type=surface);
        rock2 = ../images/groundpieces/ground/foliage/rock2.png (type=surface);
        rock3 = ../images/groundpieces/ground/foliage/rock3.png (type=surface);
        rock4 = ../images/groundpieces/ground/foliage/rock4.png (type=surface);
        rock5 = ../images/groundpieces/ground/foliage/rock5.png (type=surface);
        rock6 = ../images/groundpieces/ground/foliage/rock6.png (type=surface);
        smallbush = ../images/groundpieces/ground/foliage/smallbush.png (type=surface);
        smallbush2 = ../images/groundpieces/ground/foliage/smallbush2.png (type=surface);
        smallbush3 = ../images/groundpieces/ground/foliage/smallbush3.png (type=surface);
        talltree = ../images/groundpieces/ground/foliage/talltree.png (type=surface);
}

section green
{
        piece1 = ../images/groundpieces/ground/green/piece1.png (type=surface);
        piece2 = ../images/groundpieces/ground/green/piece2.png (type=surface);
        piece3 = ../images/groundpieces/ground/green/piece3.png (type=surface);
}

section industrial
{
        pipe1 = ../images/groundpieces/ground/industrial/pipe1.png (type=surface);
        pipe2 = ../images/groundpieces/ground/industrial/pipe2.png (type=surface);
        pipe3 = ../images/groundpieces/ground/industrial/pipe3.png (type=surface);
        pipe4 = ../images/groundpieces/ground/industrial/pipe4.png (type=surface);
        pipe5 = ../images/groundpieces/ground/industrial/pipe5.png (type=surface);
        pipe6 = ../images/groundpieces/ground/industrial/pipe6.png (type=surface);
        pipe7 = ../images/groundpieces/ground/industrial/pipe7.png (type=surface);
        pipe8 = ../images/groundpieces/ground/industrial/pipe8.png (type=surface);
        pipe_bl = ../images/groundpieces/ground/industrial/pipe_bl.png (type=surface);
        pipe_br = ../images/groundpieces/ground/industrial/pipe_br.png (type=surface);
        pipe_ul = ../images/groundpieces/ground/industrial/pipe_ul.png (type=surface);
        pipe_ur = ../images/groundpieces/ground/industrial/pipe_ur.png (type=surface);
}

section jungle
{
        branch1 = ../images/groundpieces/ground/jungle/branch1.png (type=surface);
        branch2 = ../images/groundpieces/ground/jungle/branch2.png (type=surface);
        branch3 = ../images/groundpieces/ground/jungle/branch3.png (type=surface);
        branch4 = ../images/groundpieces/ground/jungle/branch4.png (type=surface);
        branch5 = ../images/groundpieces/ground/jungle/branch5.png (type=surface);
        branch6 = ../images/groundpieces/ground/jungle/branch6.png (type=surface);
        carabatree = ../images/groundpieces/ground/jungle/carabatree.png (type=surface);
        carabatreemedium = ../images/groundpieces/ground/jungle/carabatreemedium.png (type=surface);
        carabatreesmall = ../images/groundpieces/ground/jungle/carabatreesmall.png (type=surface);
        stick1 = ../images/groundpieces/ground/jungle/stick1.png (type=surface);
        stick2 = ../images/groundpieces/ground/jungle/stick2.png (type=surface);
        stick3 = ../images/groundpieces/ground/jungle/stick3.png (type=surface);
        stick4 = ../images/groundpieces/ground/jungle/stick4.png (type=surface);
        stick5 = ../images/groundpieces/ground/jungle/stick5.png (type=surface);
        twist = ../images/groundpieces/ground/jungle/twist.png (type=surface);
        twistsmooth = ../images/groundpieces/ground/jungle/twistsmooth.png (type=surface);
}

section misc
{
        bpiece1 = ../images/groundpieces/ground/misc/bpiece1.png (type=surface);
        bpiece2 = ../images/groundpieces/ground/misc/bpiece2.png (type=surface);
        bpiece3 = ../images/groundpieces/ground/misc/bpiece3.png (type=surface);
        bpiece4 = ../images/groundpieces/ground/misc/bpiece4.png (type=surface);
        bpiece5 = ../images/groundpieces/ground/misc/bpiece5.png (type=surface);
        bpiece6 = ../images/groundpieces/ground/misc/bpiece6.png (type=surface);
        bpiece7 = ../images/groundpieces/ground/misc/bpiece7.png (type=surface);
        bpiece8 = ../images/groundpieces/ground/misc/bpiece8.png (type=surface);
        bpiece9 = ../images/groundpieces/ground/misc/bpiece9.png (type=surface);
        brick1 = ../images/groundpieces/ground/misc/brick1.png (type=surface);
        brick2 = ../images/groundpieces/ground/misc/brick2.png (type=surface);
        brick3 = ../images/groundpieces/ground/misc/brick3.png (type=surface);
        brick4 = ../images/groundpieces/ground/misc/brick4.png (type=surface);
        brick5 = ../images/groundpieces/ground/misc/brick5.png (type=surface);
        bridge1 = ../images/groundpieces/ground/misc/bridge1.png (type=surface);
        bridge2 = ../images/groundpieces/ground/misc/bridge2.png (type=surface);
        column = ../images/groundpieces/ground/misc/column.png (type=surface);
        column_down = ../images/groundpieces/ground/misc/column_down.png (type=surface);
        column_flat = ../images/groundpieces/ground/misc/column_flat.png (type=surface);
        column_flat_left = ../images/groundpieces/ground/misc/column_flat_left.png (type=surface);
        column_flat_right = ../images/groundpieces/ground/misc/column_flat_right.png (type=surface);
        column_horz = ../images/groundpieces/ground/misc/column_horz.png (type=surface);
        column_up = ../images/groundpieces/ground/misc/column_up.png (type=surface);
        column_vert = ../images/groundpieces/ground/misc/column_vert.png (type=surface);
        dragon = ../images/groundpieces/ground/misc/dragon.png (type=surface);
        green1 = ../images/groundpieces/ground/misc/green1.png (type=surface);
        green2 = ../images/groundpieces/ground/misc/green2.png (type=surface);
        grey_stone1 = ../images/groundpieces/ground/misc/grey_stone1.png (type=surface);
        grey_stone2 = ../images/groundpieces/ground/misc/grey_stone2.png (type=surface);
        grey_stone3 = ../images/groundpieces/ground/misc/grey_stone3.png (type=surface);
        grey_stone4 = ../images/groundpieces/ground/misc/grey_stone4.png (type=surface);
        grey_stone5 = ../images/groundpieces/ground/misc/grey_stone5.png (type=surface);
        grey_stone6 = ../images/groundpieces/ground/misc/grey_stone6.png (type=surface);
        pfosten = ../images/groundpieces/ground/misc/pfosten.png (type=surface);
        piece1 = ../images/groundpieces/ground/misc/piece1.png (type=surface);
        piece2 = ../images/groundpieces/ground/misc/piece2.png (type=surface);
        spike = ../images/groundpieces/ground/misc/spike.png (type=surface);
        stone0 = ../images/groundpieces/ground/misc/stone0.png (type=surface);
        stone1 = ../images/groundpieces/ground/misc/stone1.png (type=surface);
        stone2 = ../images/groundpieces/ground/misc/stone2.png (type=surface);
        stone3 = ../images/groundpieces/ground/misc/stone3.png (type=surface);
        stone4 = ../images/groundpieces/ground/misc/stone4.png (type=surface);
        stone5 = ../images/groundpieces/ground/misc/stone5.png (type=surface);
        stone6 = ../images/groundpieces/ground/misc/stone6.png (type=surface);
        stone7 = ../images/groundpieces/ground/misc/stone7.png (type=surface);
        stoneblock1 = ../images/groundpieces/ground/misc/stoneblock1.png (type=surface);
        stoneblock2 = ../images/groundpieces/ground/misc/stoneblock2.png (type=surface);
        stoneblock3 = ../images/groundpieces/ground/misc/stoneblock3.png (type=surface);
        stoneblock5 = ../images/groundpieces/ground/misc/stoneblock5.png (type=surface);
        stoneblock6 = ../images/groundpieces/ground/misc/stoneblock6.png (type=surface);
        tree = ../images/groundpieces/ground/misc/tree.png (type=surface);
        well = ../images/groundpieces/ground/misc/well.png (type=surface);
        wood1 = ../images/groundpieces/ground/misc/wood1.png (type=surface);
        wood2 = ../images/groundpieces/ground/misc/wood2.png (type=surface);
}

section mud
{
        mudpiece1 = ../images/groundpieces/ground/mud/mudpiece1.png (type=surface);
        mudpiece2 = ../images/groundpieces/ground/mud/mudpiece2.png (type=surface);
        mudpiece3 = ../images/groundpieces/ground/mud/mudpiece3.png (type=surface);
}

section mushroom
{
        toadstool1 = ../images/groundpieces/ground/mushroom/toadstool1.png (type=surface);
        toadstool2 = ../images/groundpieces/ground/mushroom/toadstool2.png (type=surface);
        toadstool3 = ../images/groundpieces/ground/mushroom/toadstool3.png (type=surface);
        toadstool4 = ../images/groundpieces/ground/mushroom/toadstool4.png (type=surface);
}

section ordina
{
        cable1 = ../images/groundpieces/ground/ordina/cable1.png (type=surface);
        cable2 = ../images/groundpieces/ground/ordina/cable2.png (type=surface);
        cdrom1 = ../images/groundpieces/ground/ordina/cdrom1.png (type=surface);
        clavier1 = ../images/groundpieces/ground/ordina/clavier1.png (type=surface);
        cpu1 = ../images/groundpieces/ground/ordina/cpu1.png (type=surface);
        ecran = ../images/groundpieces/ground/ordina/ecran.png (type=surface);
        sol2 = ../images/groundpieces/ground/ordina/sol2.png (type=surface);
        sol3 = ../images/groundpieces/ground/ordina/sol3.png (type=surface);
        sol4 = ../images/groundpieces/ground/ordina/sol4.png (type=surface);
}

section real
{
        fish = ../images/groundpieces/ground/real/fish.png (type=surface);
        green1 = ../images/groundpieces/ground/real/green1.png (type=surface);
        green2 = ../images/groundpieces/ground/real/green2.png (type=surface);
        real1 = ../images/groundpieces/ground/real/real1.png (type=surface);
        real10 = ../images/groundpieces/ground/real/real10.png (type=surface);
        real11 = ../images/groundpieces/ground/real/real11.png (type=surface);
        real12 = ../images/groundpieces/ground/real/real12.png (type=surface);
        real13 = ../images/groundpieces/ground/real/real13.png (type=surface);
        real14 = ../images/groundpieces/ground/real/real14.png (type=surface);
        real15 = ../images/groundpieces/ground/real/real15.png (type=surface);
        real16 = ../images/groundpieces/ground/real/real16.png (type=surface);
        real17 = ../images/groundpieces/ground/real/real17.png (type=surface);
        real18 = ../images/groundpieces/ground/real/real18.png (type=surface);
        real19 = ../images/groundpieces/ground/real/real19.png (type=surface);
        real2 = ../images/groundpieces/ground/real/real2.png (type=surface);
        real20 = ../images/groundpieces/ground/real/real20.png (type=surface);
        real21 = ../images/groundpieces/ground/real/real21.png (type=surface);
        real22 = ../images/groundpieces/ground/real/real22.png (type=surface);
        real23 = ../images/groundpieces/ground/real/real23.png (type=surface);
        real24 = ../images/groundpieces/ground/real/real24.png (type=surface);
        real25 = ../images/groundpieces/ground/real/real25.png (type=surface);
        real26 = ../images/groundpieces/ground/real/real26.png (type=surface);
        real27 = ../images/groundpieces/ground/real/real27.png (type=surface);
        real28 = ../images/groundpieces/ground/real/real28.png (type=surface);
        real29 = ../images/groundpieces/ground/real/real29.png (type=surface);
        real3 = ../images/groundpieces/ground/real/real3.png (type=surface);
        real30 = ../images/groundpieces/ground/real/real30.png (type=surface);
        real34 = ../images/groundpieces/ground/real/real34.png (type=surface);
        real35 = ../images/groundpieces/ground/real/real35.png (type=surface);
        real36 = ../images/groundpieces/ground/real/real36.png (type=surface);
        real37 = ../images/groundpieces/ground/real/real37.png (type=surface);
        real4 = ../images/groundpieces/ground/real/real4.png (type=surface);
        real5 = ../images/groundpieces/ground/real/real5.png (type=surface);
        real6 = ../images/groundpieces/ground/real/real6.png (type=surface);
        real7 = ../images/groundpieces/ground/real/real7.png (type=surface);
        real8 = ../images/groundpieces/ground/real/real8.png (type=surface);
        real9 = ../images/groundpieces/ground/real/real9.png (type=surface);
}

section rock
{
        blackrock1 = ../images/groundpieces/ground/rock/blackrock1.png (type=surface);
        blackrock2 = ../images/groundpieces/ground/rock/blackrock2.png (type=surface);
        blackrock3 = ../images/groundpieces/ground/rock/blackrock3.png (type=surface);
        blackrock4 = ../images/groundpieces/ground/rock/blackrock4.png (type=surface);
        stone1 = ../images/groundpieces/ground/rock/stone1.png (type=surface);
}

section signposts
{
        arrow_down = ../images/groundpieces/ground/signposts/arrow_down.png (type=surface);
        arrow_left = ../images/groundpieces/ground/signposts/arrow_left.png (type=surface);
        arrow_right = ../images/groundpieces/ground/signposts/arrow_right.png (type=surface);
        arrow_up = ../images/groundpieces/ground/signposts/arrow_up.png (type=surface);
        danger = ../images/groundpieces/ground/signposts/danger.png (type=surface);
}

section snow
{
        block1 = ../images/groundpieces/ground/snow/block1.png (type=surface);
        block2 = ../images/groundpieces/ground/snow/block2.png (type=surface);
        block3 = ../images/groundpieces/ground/snow/block3.png (type=surface);
        block4 = ../images/groundpieces/ground/snow/block4.png (type=surface);
        cabin = ../images/groundpieces/ground/snow/cabin.png (type=surface);
        cabin_winter = ../images/groundpieces/ground/snow/cabin_winter.png (type=surface);
        diablock1 = ../images/groundpieces/ground/snow/diablock1.png (type=surface);
        diablock2 = ../images/groundpieces/ground/snow/diablock2.png (type=surface);
        diablock3 = ../images/groundpieces/ground/snow/diablock3.png (type=surface);
        gpiece1 = ../images/groundpieces/ground/snow/gpiece1.png (type=surface);
        groundice = ../images/groundpieces/ground/snow/groundice.png (type=surface);
        ice1 = ../images/groundpieces/ground/snow/ice1.png (type=surface);
        ice2 = ../images/groundpieces/ground/snow/ice2.png (type=surface);
        ice3 = ../images/groundpieces/ground/snow/ice3.png (type=surface);
        iceblock1 = ../images/groundpieces/ground/snow/iceblock1.png (type=surface);
        icepiece1 = ../images/groundpieces/ground/snow/icepiece1.png (type=surface);
        igloo = ../images/groundpieces/ground/snow/igloo.png (type=surface);
        piece1 = ../images/groundpieces/ground/snow/piece1.png (type=surface);
        piece10 = ../images/groundpieces/ground/snow/piece10.png (type=surface);
        piece2 = ../images/groundpieces/ground/snow/piece2.png (type=surface);
        piece3 = ../images/groundpieces/ground/snow/piece3.png (type=surface);
        piece7 = ../images/groundpieces/ground/snow/piece7.png (type=surface);
        piece8 = ../images/groundpieces/ground/snow/piece8.png (type=surface);
        piece9 = ../images/groundpieces/ground/snow/piece9.png (type=surface);
        pillar1 = ../images/groundpieces/ground/snow/pillar1.png (type=surface);
        pillar2 = ../images/groundpieces/ground/snow/pillar2.png (type=surface);
        slopedr = ../images/groundpieces/ground/snow/slopedr.png (type=surface);
        snowball1 = ../images/groundpieces/ground/snow/snowball1.png (type=surface);
        snowman = ../images/groundpieces/ground/snow/snowman.png (type=surface);
        way = ../images/groundpieces/ground/snow/way.png (type=surface);
        xmas-tree = ../images/groundpieces/ground/snow/xmas-tree.png (type=surface);
}

section sortie
{
        ball1 = ../images/groundpieces/ground/sortie/ball1.png (type=surface);
        ball2 = ../images/groundpieces/ground/sortie/ball2.png (type=surface);
        ball3 = ../images/groundpieces/ground/sortie/ball3.png (type=surface);
        ball4 = ../images/groundpieces/ground/sortie/ball4.png (type=surface);
        column = ../images/groundpieces/ground/sortie/column.png (type=surface);
        column2 = ../images/groundpieces/ground/sortie/column2.png (type=surface);
        column3 = ../images/groundpieces/ground/sortie/column3.png (type=surface);
        plate_forme = ../images/groundpieces/ground/sortie/plate_forme.png (type=surface);
        plate_forme_left = ../images/groundpieces/ground/sortie/plate_forme_left.png (type=surface);
        plate_forme_right = ../images/groundpieces/ground/sortie/plate_forme_right.png (type=surface);
        tentacle1 = ../images/groundpieces/ground/sortie/tentacle1.png (type=surface);
}

section space
{
        block1 = ../images/groundpieces/ground/space/block1.png (type=surface);
        diagonal = ../images/groundpieces/ground/space/diagonal.png (type=surface);
        diagonalr = ../images/groundpieces/ground/space/diagonalr.png (type=surface);
        smallblock1 = ../images/groundpieces/ground/space/smallblock1.png (type=surface);
        smallblock2 = ../images/groundpieces/ground/space/smallblock2.png (type=surface);
        smallblock3 = ../images/groundpieces/ground/space/smallblock3.png (type=surface);
        smalltower = ../images/groundpieces/ground/space/smalltower.png (type=surface);
        tower1 = ../images/groundpieces/ground/space/tower1.png (type=surface);
        way = ../images/groundpieces/ground/space/way.png (type=surface);
}

section sweets
{
        allsort1 = ../images/groundpieces/ground/sweets/allsort1.png (type=surface);
        allsort2 = ../images/groundpieces/ground/sweets/allsort2.png (type=surface);
        aquachoc = ../images/groundpieces/ground/sweets/aquachoc.png (type=surface);
        cake1 = ../images/groundpieces/ground/sweets/cake1.png (type=surface);
        cake2 = ../images/groundpieces/ground/sweets/cake2.png (type=surface);
        cake3 = ../images/groundpieces/ground/sweets/cake3.png (type=surface);
        cake4 = ../images/groundpieces/ground/sweets/cake4.png (type=surface);
        cake5 = ../images/groundpieces/ground/sweets/cake5.png (type=surface);
        canestalk = ../images/groundpieces/ground/sweets/canestalk.png (type=surface);
        canestub = ../images/groundpieces/ground/sweets/canestub.png (type=surface);
        canetop = ../images/groundpieces/ground/sweets/canetop.png (type=surface);
        chocbar = ../images/groundpieces/ground/sweets/chocbar.png (type=surface);
        chocbloc-lowleft = ../images/groundpieces/ground/sweets/chocbloc-lowleft.png (type=surface);
        chocbloc-lowright = ../images/groundpieces/ground/sweets/chocbloc-lowright.png (type=surface);
        chocbloc-topleft = ../images/groundpieces/ground/sweets/chocbloc-topleft.png (type=surface);
        chocbloc-topright = ../images/groundpieces/ground/sweets/chocbloc-topright.png (type=surface);
        chocbloc = ../images/groundpieces/ground/sweets/chocbloc.png (type=surface);
        goldchoc = ../images/groundpieces/ground/sweets/goldchoc.png (type=surface);
        greenjellybaby = ../images/groundpieces/ground/sweets/greenjellybaby.png (type=surface);
        icecream = ../images/groundpieces/ground/sweets/icecream.png (type=surface);
        jube1 = ../images/groundpieces/ground/sweets/jube1.png (type=surface);
        jube2 = ../images/groundpieces/ground/sweets/jube2.png (type=surface);
        lollipop-purp = ../images/groundpieces/ground/sweets/lollipop-purp.png (type=surface);
        lollipop = ../images/groundpieces/ground/sweets/lollipop.png (type=surface);
        mmblue = ../images/groundpieces/ground/sweets/mmblue.png (type=surface);
        mmbrown = ../images/groundpieces/ground/sweets/mmbrown.png (type=surface);
        mmred = ../images/groundpieces/ground/sweets/mmred.png (type=surface);
        mmyellow = ../images/groundpieces/ground/sweets/mmyellow.png (type=surface);
        purpchoc = ../images/groundpieces/ground/sweets/purpchoc.png (type=surface);
        purplechoc = ../images/groundpieces/ground/sweets/purplechoc.png (type=surface);
        redjellybaby = ../images/groundpieces/ground/sweets/redjellybaby.png (type=surface);
}

section test
{
        test1 = ../images/groundpieces/ground/test/test1.png (type=surface);
        test10 = ../images/groundpieces/ground/test/test10.png (type=surface);
        test2 = ../images/groundpieces/ground/test/test2.png (type=surface);
        test3 = ../images/groundpieces/ground/test/test3.png (type=surface);
        test4 = ../images/groundpieces/ground/test/test4.png (type=surface);
        test5 = ../images/groundpieces/ground/test/test5.png (type=surface);
        test6 = ../images/groundpieces/ground/test/test6.png (type=surface);
        test7 = ../images/groundpieces/ground/test/test7.png (type=surface);
        test8 = ../images/groundpieces/ground/test/test8.png (type=surface);
        test9 = ../images/groundpieces/ground/test/test9.png (type=surface);
}

// EOF //
