// Automatic generated by gen-scrfile.scm - don't edit by hand!

section desert
{
        bigdimwall = ../images/hotspots/desert/bigdimwall.png (type=surface);
        mediumdimwall = ../images/hotspots/desert/mediumdimwall.png (type=surface);
        mediumegyptpic = ../images/hotspots/desert/mediumegyptpic.png (type=surface);
        mediummummy = ../images/hotspots/desert/mediummummy.png (type=surface);
        mediumsphinx = ../images/hotspots/desert/mediumsphinx.png (type=surface);
        smallD = ../images/hotspots/desert/smallD.png (type=surface);
        smallE = ../images/hotspots/desert/smallE.png (type=surface);
        smallG = ../images/hotspots/desert/smallG.png (type=surface);
        smallO = ../images/hotspots/desert/smallO.png (type=surface);
        smalldimwall = ../images/hotspots/desert/smalldimwall.png (type=surface);
        smallegyptpic = ../images/hotspots/desert/smallegyptpic.png (type=surface);
        smallmummy = ../images/hotspots/desert/smallmummy.png (type=surface);
        smallsphinx = ../images/hotspots/desert/smallsphinx.png (type=surface);
}

section misc
{
        bridge = ../images/hotspots/misc/bridge.png (type=surface);
        tree = ../images/hotspots/misc/tree.png (type=surface);
}

section signposts
{
        arrow_east = ../images/hotspots/signposts/arrow_east.png (type=surface);
        arrow_north = ../images/hotspots/signposts/arrow_north.png (type=surface);
        arrow_northeast = ../images/hotspots/signposts/arrow_northeast.png (type=surface);
        arrow_northwest = ../images/hotspots/signposts/arrow_northwest.png (type=surface);
        arrow_south = ../images/hotspots/signposts/arrow_south.png (type=surface);
        arrow_southeast = ../images/hotspots/signposts/arrow_southeast.png (type=surface);
        arrow_southwest = ../images/hotspots/signposts/arrow_southwest.png (type=surface);
        arrow_west = ../images/hotspots/signposts/arrow_west.png (type=surface);
        basher = ../images/hotspots/signposts/basher.png (type=surface);
        blocker = ../images/hotspots/signposts/blocker.png (type=surface);
        bomber = ../images/hotspots/signposts/bomber.png (type=surface);
        bridger = ../images/hotspots/signposts/bridger.png (type=surface);
        climber = ../images/hotspots/signposts/climber.png (type=surface);
        danger = ../images/hotspots/signposts/danger.png (type=surface);
        digger = ../images/hotspots/signposts/digger.png (type=surface);
        floater = ../images/hotspots/signposts/floater.png (type=surface);
        miner = ../images/hotspots/signposts/miner.png (type=surface);
        nogo = ../images/hotspots/signposts/nogo.png (type=surface);
}

section space
{
        engine = ../images/hotspots/space/engine.png (type=surface);
}

// EOF //
