;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/actions.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20)
      (slider 20))
    (music "none")
    (levelsize 1216 608))
  (objects 
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 386 290 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 528 290 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 677 290 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 372 357 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 513 354 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 653 352 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 421 415 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 550 412 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 685 201 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar2")
        (modifier "ROT0"))
      (position 327 93 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 318 220 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 373 208 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 965 247 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 896 295 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 259 288 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 237 356 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 291 415 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 186 239 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 137 305 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 113 367 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 165 417 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 897 403 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/middleprickpiece")
        (modifier "ROT0"))
      (position 763 291 0))
    (entrance 
      (position 565 217 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 760 168 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (surface-background 
      (surface 
        (image "textures/anim_fire")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))))
;; EOF ;;
