;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/basher.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (bomber 20)
      (digger 20)
      (miner 20)
      (bridger 20))
    (music "none")
    (levelsize 1216 608))
  (objects 
    (surface-background 
      (surface 
        (image "textures/nightjungle")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 409 213 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 496 213 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 409 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 496 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 409 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 496 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 409 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 496 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 235 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 322 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 235 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 322 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 581 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 668 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 581 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 668 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 137 232 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 224 232 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 137 277 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 224 277 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 729 214 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 816 214 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 729 259 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 816 259 0))
    (entrance 
      (position 502 177 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 445 254 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 505 254 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 360 353 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 412 337 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 308 342 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 615 330 0))))
;; EOF ;;
