;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/bla.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time 9000)
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1216 600))
  (objects 
    (infobox 
      (position 382 243 0))))
;; EOF ;;
