;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/blablub.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (music "none")
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20)
      (slider 20))
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/happyclouds")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position -90 13 -150))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_flat_left")
        (modifier "ROT90"))
      (position 305 454 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_flat_left")
        (modifier "ROT90"))
      (position 548 456 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/column_flat_left")
        (modifier "ROT90"))
      (position 426 489 0))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -40 525 -50)
      (repeat 21)
      (speed 55))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -76 538 100)
      (repeat 21)
      (speed 60))))
;; EOF ;;
