;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/climber.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1216 608))
  (objects 
    (surface-background 
      (surface 
        (image "textures/desert_room")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 751 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 649 209 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 834 245 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 651 255 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 831 291 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 652 294 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 229 255 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 229 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 829 336 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 652 337 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 229 298 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 229 387 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 828 382 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 652 382 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 809 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 461 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 635 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 287 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 722 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 374 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 548 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 200 427 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test9")
        (modifier "ROT0"))
      (position 295 196 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test10")
        (modifier "ROT0"))
      (position 243 201 0))
    (entrance 
      (position 479 331 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 803 325 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 260 323 0))
    (groundpiece 
      (type "bridge")
      (surface 
        (image "groundpieces/bridge/space/grid1")
        (modifier "ROT0"))
      (position 660 355 0))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position 678 198 0)
      (repeat 5)
      (speed 50))))
;; EOF ;;
