;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/crash_on_entrance_remove.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 20)
    (number-to-save 15)
    (time -1)
    (difficulty 20)
    (playable 0)
    (comment )
    (music "none")
    (actions 
      (blocker 5)
      (bomber 5)
      (bridger 10)
      (digger 5)
      (floater 5)
      (jumper 40))
    (levelsize 2000 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/clouds2")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x -1.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 6 -58 -150))
    (spike 
      (position 977.691 345.415 -100))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 839 165 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT270"))
      (position 843 24 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 885 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 619 298 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 572 253 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 751 120 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 929 165 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT180FLIP"))
      (position 573 343 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 663 254 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 617 209 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT180FLIP"))
      (position 481 343 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 527 298 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 709 209 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 707 120 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 883 121 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 753 165 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1109 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 663 164 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 1064 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 797 120 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 974 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 842 120 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 930 254 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 754 118 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 1020 255 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 818 118 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1018 210 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 861 118 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT180FLIP"))
      (position 975 300 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 937 249 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 856 500 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 894 505 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 683 365 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 334 372 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 515 374 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 919 421 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock3")
        (modifier "ROT0"))
      (position 876 418 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 872 379 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock3")
        (modifier "ROT0FLIP"))
      (position 963 379 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 918 379 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT180FLIP"))
      (position 874 466 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 247 370 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 493 396 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 285 400 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180FLIP"))
      (position 322 442 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180FLIP"))
      (position 556 457 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180FLIP"))
      (position 391 478 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 612 369 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 733 414 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 596 364 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 671 362 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 736 362 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1128 208 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 800 362 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1085 208 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 355 367 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 318 366 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 419 367 0))
    (exit 
      (owner-id 0)
      (position 1866.47 268.245 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1750 268 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 1796 268 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1021 208 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1841 268 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1753 266 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1817 266 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1860 266 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1118 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 1164 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1209 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1110 512 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1227 512 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1171 513 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1297 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 1343 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1388 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1289 512 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1406 512 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1350 513 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 944 377 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 975 313 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 1335 219 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 1519 222 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1661 268 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1661 266 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT180FLIP"))
      (position 1706 269 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1711 266 0))
    (entrance 
      (position 1068 136 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 1388.47 516.245 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 291.668 227.283 -50)
      (speed -1)
      (parallax 1))
    (entrance 
      (position 339.357 269.143 0)
      (type "generic")
      (direction "right")
      (release-rate 150)
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 291.688 227.332 100)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -42 526 -50)
      (repeat 33)
      (speed 55))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -78 539 100)
      (repeat 33)
      (speed 60))))
;; EOF ;;
