;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/faller.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Fall and splash test")
    (description "Do not enter if you don't like splashing penguins... ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 100)
    (number-to-save 50)
    (time 9000)
    (difficulty 5)
    (playable 0)
    (comment )
    (music "none")
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/crystal")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 0 0 -10))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 428 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 83 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 884 533 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 675 256 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 514 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 169 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 971 533 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 762 256 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 601 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 256 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 1117 339 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 849 256 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 688 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test3")
        (modifier "ROT0"))
      (position 343 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT0"))
      (position 276 34 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "global/Hotspots/down_arrow")
        (modifier "ROT0"))
      (position 352 119 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "global/Hotspots/up_arrow")
        (modifier "ROT0"))
      (position 361 483 0))
    (entrance 
      (position 507 263 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 449 264 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 390 265 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 333 266 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 275 267 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 832 131 0)
      (type "generic")
      (direction "misc")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 561 262 0)
      (type "generic")
      (direction "left")
      (release-rate 25)
      (owner-id 0))))
;; EOF ;;
