;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/newgroundpiece.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20)
      (slider 20))
    (music "none")
    (levelsize 1216 608))
  (objects 
    (surface-background 
      (surface 
        (image "textures/industrial")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 -150))
    (groundpiece 
      (surface 
        (image "groundpieces/ground/misc/bpiece8")
        (modifier "ROT0"))
      (position 323 251 0))
    (groundpiece 
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 309 371 0))
    (groundpiece 
      (surface 
        (image "groundpieces/ground/misc/bpiece7")
        (modifier "ROT0"))
      (position 193 374 0))
    (entrance 
      (position 374 207 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))))
;; EOF ;;
