;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/rotation.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 40)
    (playable 0)
    (comment )
    (music "none")
    (actions )
    (levelsize 1024 768))
  (objects 
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT0"))
      (position 215 162 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT90"))
      (position 366 260 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT180"))
      (position 195 433 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT270"))
      (position 116 247 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT0FLIP"))
      (position 638 174 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT90FLIP"))
      (position 789 272 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT180FLIP"))
      (position 618 445 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/signposts/danger")
        (modifier "ROT270FLIP"))
      (position 531 261 0))
    (solidcolor-background 
      (color 0 0 0 1))))
;; EOF ;;
