;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/sorting.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Entering the pyramid")
    (description "After their long and dangerous journey through the desert they finally reach "
                 "the large pyramid...")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 30)
    (time 9000)
    (difficulty 50)
    (playable 1)
    (comment "- stuck under bridge bug")
    (actions 
      (basher 1)
      (blocker 10)
      (bomber 10)
      (bridger 10))
    (music "none")
    (levelsize 1600 600))
  (objects 
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigsand")
        (modifier "ROT0"))
      (position 508 375 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/pillar2")
        (modifier "ROT0"))
      (position 628 320 42))))
;; EOF ;;
