;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/test20.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time -1)
    (difficulty 0)
    (playable 0)
    (comment )
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1216 608))
  (objects 
    (surface-background 
      (surface 
        (image "textures/desert_room")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (position 227 32 -150))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 647 366 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 279 365 0))
    (entrance 
      (position 775 272 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 424 270 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 754 439 0))
    (groundpiece 
      (type "transparent")
      (surface 
        (image "groundpieces/transparent/misc/moos1")
        (modifier "ROT0"))
      (position 374 428 0))
    (entrance 
      (position 618 492 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/test/test2")
        (modifier "ROT0"))
      (position 585 581 0))))
;; EOF ;;
