;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/test13.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Hard work to dig!")
    (description "This level demonstrates the woodthing entrance. Its is not meant to be finished "
                 "or playable.")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 100)
    (number-to-save 50)
    (time -1)
    (actions 
      (rocketlauncher 20)
      (angel 20)
      (boarder 20)
      (superman 20)
      (basher 20)
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (miner 20))
    (music "none")
    (levelsize 1728 864))
  (objects 
    (surface-background 
      (surface 
        (image "textures/Textures/nebula")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 1.0)
      (scroll-y 0.0)
      (para-x 0.2)
      (para-y 0.2)
      (stretch-x 0)
      (stretch-y 0)
      (position 243 21 -400))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -8 791 -100)
      (repeat 17)
      (speed 50))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 771 709 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 758 733 0))
    (surface-background 
      (surface 
        (image "textures/cyanspace")
        (modifier "ROT0"))
      (color 0 0 0 0.1)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.1)
      (para-y 0.1)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 0))
    (surface-background 
      (surface 
        (image "textures/thunderstorm")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 1.0)
      (scroll-y 0.0)
      (para-x 0.2)
      (para-y 0.2)
      (stretch-x 0)
      (stretch-y 0)
      (position 0 0 0))
    (entrance 
      (position 1421 464 0)
      (type "woodthing")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 734 179 0)
      (type "woodthing")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (entrance 
      (position 399 396 0)
      (type "woodthing")
      (direction "left")
      (release-rate 25)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 375 490 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 715 765 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 670 765 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 691 729 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 273 511 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 620 274 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 504 510 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 311 521 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 426 513 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 291 624 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 212 548 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 1404 600 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 234 570 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 273 528 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 734 386 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 565 306 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 644 306 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1404 720 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 252 646 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 279 787 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 266 700 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 231 531 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1036 461 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 958 403 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1092 501 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1006 527 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 496 511 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 658 488 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 825 390 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 959 494 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1048 578 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 864 479 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 827 444 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 652 541 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1024 599 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 982 705 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1085 685 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 524 590 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 884 757 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 908 723 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 629 587 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 392 499 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 961 636 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 994 738 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 236 601 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 1281 715 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 384 787 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 942 734 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1337 617 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1381 570 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1204 610 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1182 589 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1235 559 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece5")
        (modifier "ROT0"))
      (position 1118 563 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1051 618 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 772 378 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece4")
        (modifier "ROT0"))
      (position 734 288 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 357 789 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 433 787 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece1")
        (modifier "ROT0"))
      (position 408 789 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1354 810 41))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/bpiece6")
        (modifier "ROT0"))
      (position 1454 810 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 685 447 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 651 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 779 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 460 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 587 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 715 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 396 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 268 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 523 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 332 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 204 615 41))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 676 510 41))
    (liquid 
      (surface 
        (image "liquids/slime")
        (modifier "ROT0"))
      (position -37 807 100)
      (repeat 17)
      (speed 50))
    (hotspot 
      (surface 
        (image "entrances/woodthing_nmov")
        (modifier "ROT0"))
      (position 1345 329 100)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "entrances/woodthing_nmov")
        (modifier "ROT0"))
      (position 658 44 100)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "entrances/woodthing_nmov")
        (modifier "ROT0"))
      (position 323 261 100)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 366 486 400))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 552 486 400))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 428 486 400))
    (surface-background 
      (surface 
        (image "textures/Textures/nebula")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 1.0)
      (scroll-y 0.0)
      (para-x 0.2)
      (para-y 0.2)
      (stretch-x 0)
      (stretch-y 0)
      (position 75 77 450))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 491 486 550))
    (surface-background 
      (surface 
        (image "textures/Textures/nebula")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 1.0)
      (scroll-y 0.0)
      (para-x 0.2)
      (para-y 0.2)
      (stretch-x 0)
      (stretch-y 0)
      (position 243 21 -400))))
;; EOF ;;
