;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/test7.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "PLE Level")
    (description "This level has no name ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time 9000)
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/default")
        (modifier "ROT0"))
      (color 0 0 0 1)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigblock-broken2")
        (modifier "ROT0"))
      (position 559 268 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigblock-broken2")
        (modifier "ROT0"))
      (position 259 418 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigprickpiece")
        (modifier "ROT0"))
      (position 513 412 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/desert/bigblock-broken1")
        (modifier "ROT0"))
      (position 813 412 0))
    (entrance 
      (position 749 218 0)
      (type "generic")
      (direction "misc")
      (release-rate 50))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -32 736 -100)
      (repeat 16)
      (speed 50))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -32 736 -100)
      (repeat 16)
      (speed 50))))
;; EOF ;;
