;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/test11.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short description")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time 9000)
    (actions 
      (boarder 20)
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1216 1024))
  (objects 
    (surface-background 
      (surface 
        (image "textures/clouds")
        (modifier "ROT0"))
      (color 0 0 0 0.8)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 552 121 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 552 170 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 552 225 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 447 273 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 240 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 713 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 896 221 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 676 274 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 477 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 950 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 333 273 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 126 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 145 585 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 599 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 782 221 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 562 274 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 358 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 831 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 506 273 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 299 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 772 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 955 221 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 735 274 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 536 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 1009 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 995 582 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 391 273 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 184 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 657 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 840 221 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 564 475 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 331 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 515 475 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 282 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 462 475 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 229 419 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 620 274 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 421 630 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stoneblock1")
        (modifier "ROT0"))
      (position 894 630 0))
    (entrance 
      (position 694 204 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 694 204 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 694 204 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 440 211 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 440 211 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 440 211 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (entrance 
      (position 695 512 0)
      (type "generic")
      (direction "misc")
      (release-rate 50)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 587 475 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))))
;; EOF ;;
