;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/test/test10.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "EditorDefaultValue: Please give me a name...")
    (description "EditorDefaultValue: ...and a short descriptions")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 50)
    (number-to-save 25)
    (time 9000)
    (actions 
      (basher 20)
      (blocker 20)
      (bomber 20)
      (bridger 20)
      (climber 20)
      (digger 20)
      (floater 20)
      (jumper 20)
      (miner 20))
    (music "none")
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/clouds")
        (modifier "ROT0"))
      (color 0 0 0 0.8)
      (scroll-x 50.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0))
    (conveyorbelt 
      (position 456 227 0)
      (width 5)
      (speed 55))
    (conveyorbelt 
      (position 390 274 0)
      (width 15)
      (speed 52))
    (conveyorbelt 
      (position 444 326 0)
      (width 5)
      (speed 52))
    (conveyorbelt 
      (position 391 376 0)
      (width 5)
      (speed 52))
    (conveyorbelt 
      (position 386 172 0)
      (width 5)
      (speed 52))
    (entrance 
      (position 472 129 0)
      (type "generic")
      (direction "misc")
      (release-rate 50))))
;; EOF ;;
