s%entrances/Entrances/cloud%entrances/cloud%g
s%entrances/Entrances/entrance%entrances/entrance%g
s%entrances/Entrances/entrance_eyes%entrances/entrance_eyes%g
s%entrances/Entrances/entrance_eyes_anim%entrances/entrance_eyes_anim%g
s%entrances/Entrances/generic%entrances/generic%g
s%entrances/Entrances/industrial%entrances/industrial%g
s%entrances/Entrances/industrial_top%entrances/industrial_top%g
s%entrances/Entrances/snow_back%entrances/snow_back%g
s%entrances/Entrances/snow_front%entrances/snow_front%g
s%entrances/Entrances/space%entrances/space%g
s%entrances/Entrances/underlay_eyes%entrances/underlay_eyes%g
s%entrances/Entrances/wood_bottom%entrances/wood_bottom%g
s%entrances/Entrances/wood_top%entrances/wood_top%g
s%entrances/Entrances/woodthing_mov%entrances/woodthing_mov%g
s%entrances/Entrances/woodthing_nmov%entrances/woodthing_nmov%g
s%entrances/entrances/cloud%entrances/cloud%g
s%entrances/entrances/entrance%entrances/entrance%g
s%entrances/entrances/entrance_eyes%entrances/entrance_eyes%g
s%entrances/entrances/entrance_eyes_anim%entrances/entrance_eyes_anim%g
s%entrances/entrances/generic%entrances/generic%g
s%entrances/entrances/industrial%entrances/industrial%g
s%entrances/entrances/industrial_top%entrances/industrial_top%g
s%entrances/entrances/snow_back%entrances/snow_back%g
s%entrances/entrances/snow_front%entrances/snow_front%g
s%entrances/entrances/space%entrances/space%g
s%entrances/entrances/underlay_eyes%entrances/underlay_eyes%g
s%entrances/entrances/wood_bottom%entrances/wood_bottom%g
s%entrances/entrances/wood_top%entrances/wood_top%g
s%entrances/entrances/woodthing_mov%entrances/woodthing_mov%g
s%entrances/entrances/woodthing_nmov%entrances/woodthing_nmov%g
s%exits/Exits/crystal%exits/crystal%g
s%exits/Exits/desert%exits/desert%g
s%exits/Exits/desert_tut%exits/desert_tut%g
s%exits/Exits/ice%exits/ice%g
s%exits/Exits/ice2%exits/ice2%g
s%exits/Exits/industrial%exits/industrial%g
s%exits/Exits/mud%exits/mud%g
s%exits/Exits/ordina%exits/ordina%g
s%exits/Exits/sortie%exits/sortie%g
s%exits/Exits/sortie_anim%exits/sortie_anim%g
s%exits/Exits/space%exits/space%g
s%exits/Exits/stone%exits/stone%g
s%exits/Exits/sweetexit%exits/sweetexit%g
s%exits/exits/crystal%exits/crystal%g
s%exits/exits/desert%exits/desert%g
s%exits/exits/desert_tut%exits/desert_tut%g
s%exits/exits/ice%exits/ice%g
s%exits/exits/ice2%exits/ice2%g
s%exits/exits/industrial%exits/industrial%g
s%exits/exits/mud%exits/mud%g
s%exits/exits/ordina%exits/ordina%g
s%exits/exits/sortie%exits/sortie%g
s%exits/exits/sortie_anim%exits/sortie_anim%g
s%exits/exits/space%exits/space%g
s%exits/exits/stone%exits/stone%g
s%exits/exits/sweetexit%exits/sweetexit%g
s%global/Buttons/pause%core/buttons/pause%g
s%global/Entrances/cloud%entrances/cloud%g
s%global/Entrances/entrance%entrances/entrance%g
s%global/Entrances/entrance_eyes%entrances/entrance_eyes%g
s%global/Entrances/entrance_eyes_anim%entrances/entrance_eyes_anim%g
s%global/Entrances/generic%entrances/generic%g
s%global/Entrances/industrial%entrances/industrial%g
s%global/Entrances/industrial_top%entrances/industrial_top%g
s%global/Entrances/space%entrances/space%g
s%global/Entrances/underlay_eyes%entrances/underlay_eyes%g
s%global/Entrances/wood_bottom%entrances/wood_bottom%g
s%global/Entrances/wood_top%entrances/wood_top%g
s%global/Entrances/woodthing_mov%entrances/woodthing_mov%g
s%global/Entrances/woodthing_nmov%entrances/woodthing_nmov%g
s%global/Exits/crystal%exits/crystal%g
s%global/Exits/desert%exits/desert%g
s%global/Exits/desert_tut%exits/desert_tut%g
s%global/Exits/ice%exits/ice%g
s%global/Exits/industrial%exits/industrial%g
s%global/Exits/sortie%exits/sortie%g
s%global/Exits/sortie_1%exits/ordina%g
s%global/Exits/sortie_anim%exits/sortie_anim%g
s%global/Exits/space%exits/space%g
s%global/Exits/stone%exits/stone%g
s%global/Exits/sweetexit%exits/sweetexit%g
s%global/Grass/grass1%groundpieces/transparent/foliage/grass1%g
s%global/Grass/grass10%groundpieces/transparent/foliage/grass10%g
s%global/Grass/grass11%groundpieces/transparent/foliage/grass11%g
s%global/Grass/grass12%groundpieces/transparent/foliage/grass12%g
s%global/Grass/grass13%groundpieces/transparent/foliage/grass13%g
s%global/Grass/grass14%groundpieces/transparent/foliage/grass14%g
s%global/Grass/grass15%groundpieces/transparent/foliage/grass15%g
s%global/Grass/grass16%groundpieces/transparent/foliage/grass16%g
s%global/Grass/grass2%groundpieces/transparent/foliage/grass2%g
s%global/Grass/grass3%groundpieces/transparent/foliage/grass3%g
s%global/Grass/grass4%groundpieces/transparent/foliage/grass4%g
s%global/Grass/grass5%groundpieces/transparent/foliage/grass5%g
s%global/Grass/grass6%groundpieces/transparent/foliage/grass6%g
s%global/Grass/grass7%groundpieces/transparent/foliage/grass7%g
s%global/Grass/grass8%groundpieces/transparent/foliage/grass8%g
s%global/Grass/grass9%groundpieces/transparent/foliage/grass9%g
s%global/GroundPieces/Crystal/block%groundpieces/ground/crystal/block%g
s%global/GroundPieces/Crystal/column%groundpieces/ground/crystal/column%g
s%global/GroundPieces/Crystal/diagcrystal%groundpieces/ground/crystal/diagcrystal%g
s%global/GroundPieces/Crystal/hexcrystal%groundpieces/ground/crystal/hexcrystal%g
s%global/GroundPieces/Crystal/horiz%groundpieces/ground/crystal/horiz%g
s%global/GroundPieces/Crystal/horiz2%groundpieces/ground/crystal/horiz2%g
s%global/GroundPieces/Crystal/pipe%groundpieces/ground/crystal/pipe%g
s%global/GroundPieces/Crystal/pipeend%groundpieces/ground/crystal/pipeend%g
s%global/GroundPieces/Crystal/platform%groundpieces/ground/crystal/platform%g
s%global/GroundPieces/Crystal/platform2%groundpieces/ground/crystal/platform2%g
s%global/GroundPieces/Crystal/pointleft%groundpieces/ground/crystal/pointleft%g
s%global/GroundPieces/Crystal/pointright%groundpieces/ground/crystal/pointright%g
s%global/GroundPieces/Crystal/skinnycrystal%groundpieces/ground/crystal/skinnycrystal%g
s%global/GroundPieces/Crystal/smcrystal%groundpieces/ground/crystal/smcrystal%g
s%global/GroundPieces/Crystal/tesselate%groundpieces/ground/crystal/tesselate%g
s%global/GroundPieces/Desert/Sluggydu%groundpieces/ground/desert/sluggydu%g
s%global/GroundPieces/Desert/bigblock-broken1%groundpieces/ground/desert/bigblock-broken1%g
s%global/GroundPieces/Desert/bigblock-broken2%groundpieces/ground/desert/bigblock-broken2%g
s%global/GroundPieces/Desert/bigdune1%groundpieces/ground/desert/bigdune1%g
s%global/GroundPieces/Desert/bigprickpiece%groundpieces/ground/desert/bigprickpiece%g
s%global/GroundPieces/Desert/blobdune%groundpieces/ground/desert/blobdune%g
s%global/GroundPieces/Desert/domedune%groundpieces/ground/desert/domedune%g
s%global/GroundPieces/Desert/flatdune%groundpieces/ground/desert/flatdune%g
s%global/GroundPieces/Desert/middleprickpiece%groundpieces/ground/desert/middleprickpiece%g
s%global/GroundPieces/Desert/peakdune%groundpieces/ground/desert/peakdune%g
s%global/GroundPieces/Desert/pillar1%groundpieces/ground/desert/pillar1%g
s%global/GroundPieces/Desert/pillar2%groundpieces/ground/desert/pillar2%g
s%global/GroundPieces/Desert/pillar3%groundpieces/ground/desert/pillar3%g
s%global/GroundPieces/Desert/smallbrickpiece%groundpieces/ground/desert/smallbrickpiece%g
s%global/GroundPieces/Foliage/flax1%groundpieces/ground/foliage/flax1%g
s%global/GroundPieces/Foliage/flax2%groundpieces/ground/foliage/flax2%g
s%global/GroundPieces/Foliage/midtree1%groundpieces/ground/foliage/midtree1%g
s%global/GroundPieces/Foliage/midtree2%groundpieces/ground/foliage/midtree2%g
s%global/GroundPieces/Foliage/oak1%groundpieces/ground/foliage/oak1%g
s%global/GroundPieces/Foliage/smallbush%groundpieces/ground/foliage/smallbush%g
s%global/GroundPieces/Foliage/smallbush2%groundpieces/ground/foliage/smallbush2%g
s%global/GroundPieces/Foliage/smallbush3%groundpieces/ground/foliage/smallbush3%g
s%global/GroundPieces/Foliage/talltree%groundpieces/ground/foliage/talltree%g
s%global/GroundPieces/Foliage/turfconcave%groundpieces/transparent/foliage/turfconcave%g
s%global/GroundPieces/Foliage/turfflat%groundpieces/transparent/foliage/turfflat%g
s%global/GroundPieces/Foliage/turfslopeleft%groundpieces/transparent/foliage/turfslopeleft%g
s%global/GroundPieces/Foliage/turfslopeleft20%groundpieces/transparent/foliage/turfslopeleft20%g
s%global/GroundPieces/Foliage/turfsloperight%groundpieces/transparent/foliage/turfsloperight%g
s%global/GroundPieces/Foliage/turfsloperight20%groundpieces/transparent/foliage/turfsloperight20%g
s%global/GroundPieces/Foliage/turfsmallbump%groundpieces/transparent/foliage/turfsmallbump%g
s%global/GroundPieces/Foliage/turfsmallnook%groundpieces/transparent/foliage/turfsmallnook%g
s%global/GroundPieces/Foliage/turftufty%groundpieces/transparent/foliage/turftufty%g
s%global/GroundPieces/Jungle/branch1%groundpieces/ground/jungle/branch1%g
s%global/GroundPieces/Jungle/branch2%groundpieces/ground/jungle/branch2%g
s%global/GroundPieces/Jungle/branch3%groundpieces/ground/jungle/branch3%g
s%global/GroundPieces/Jungle/branch4%groundpieces/ground/jungle/branch4%g
s%global/GroundPieces/Jungle/branch5%groundpieces/ground/jungle/branch5%g
s%global/GroundPieces/Jungle/branch6%groundpieces/ground/jungle/branch6%g
s%global/GroundPieces/Jungle/carabatree%groundpieces/ground/jungle/carabatree%g
s%global/GroundPieces/Jungle/carabatreemedium%groundpieces/ground/jungle/carabatreemedium%g
s%global/GroundPieces/Jungle/carabatreesmall%groundpieces/ground/jungle/carabatreesmall%g
s%global/GroundPieces/Jungle/stick1%groundpieces/ground/jungle/stick1%g
s%global/GroundPieces/Jungle/stick2%groundpieces/ground/jungle/stick2%g
s%global/GroundPieces/Jungle/stick3%groundpieces/ground/jungle/stick3%g
s%global/GroundPieces/Jungle/stick4%groundpieces/ground/jungle/stick4%g
s%global/GroundPieces/Jungle/stick5%groundpieces/ground/jungle/stick5%g
s%global/GroundPieces/Jungle/twist%groundpieces/ground/jungle/twist%g
s%global/GroundPieces/Jungle/twistsmooth%groundpieces/ground/jungle/twistsmooth%g
s%global/GroundPieces/Misc/bigprickpiece%groundpieces/ground/desert/bigprickpiece%g
s%global/GroundPieces/Misc/brick1%groundpieces/ground/misc/brick1%g
s%global/GroundPieces/Misc/brick2%groundpieces/ground/misc/brick2%g
s%global/GroundPieces/Misc/brick3%groundpieces/ground/misc/brick3%g
s%global/GroundPieces/Misc/brick4%groundpieces/ground/misc/brick4%g
s%global/GroundPieces/Misc/bridge1%groundpieces/ground/misc/bridge1%g
s%global/GroundPieces/Misc/bridge_left%groundpieces/bridge/misc/bridge_left%g
s%global/GroundPieces/Misc/bridge_right%groundpieces/bridge/misc/bridge_right%g
s%global/GroundPieces/Misc/middleprickpiece%groundpieces/ground/desert/middleprickpiece%g
s%global/GroundPieces/Misc/pfosten%groundpieces/ground/misc/pfosten%g
s%global/GroundPieces/Misc/piece1%groundpieces/ground/misc/piece1%g
s%global/GroundPieces/Misc/piece2%groundpieces/ground/misc/piece2%g
s%global/GroundPieces/Misc/piece3%groundpieces/ground/snow/piece3%g
s%global/GroundPieces/Misc/piece7%groundpieces/ground/snow/piece7%g
s%global/GroundPieces/Misc/piece8%groundpieces/ground/snow/piece8%g
s%global/GroundPieces/Misc/piece9%groundpieces/ground/snow/piece9%g
s%global/GroundPieces/Misc/smallbrickpiece%groundpieces/ground/desert/smallbrickpiece%g
s%global/GroundPieces/Misc/spike%groundpieces/ground/misc/spike%g
s%global/GroundPieces/Misc/stoneblock1%groundpieces/ground/misc/stoneblock1%g
s%global/GroundPieces/Misc/stoneblock2%groundpieces/ground/misc/stoneblock2%g
s%global/GroundPieces/Misc/stoneblock3%groundpieces/ground/misc/stoneblock3%g
s%global/GroundPieces/Misc/stoneblock5%groundpieces/ground/misc/stoneblock5%g
s%global/GroundPieces/Misc/stoneblock6%groundpieces/ground/misc/stoneblock6%g
s%global/GroundPieces/Misc/way%groundpieces/ground/desert/platform%g
s%global/GroundPieces/Misc/way_left%groundpieces/ground/desert/platform_left%g
s%global/GroundPieces/Misc/way_right%groundpieces/ground/desert/platform_right%g
s%global/GroundPieces/Mushroom/toadstool1%groundpieces/ground/mushroom/toadstool1%g
s%global/GroundPieces/Mushroom/toadstool2%groundpieces/ground/mushroom/toadstool2%g
s%global/GroundPieces/Mushroom/toadstool3%groundpieces/ground/mushroom/toadstool3%g
s%global/GroundPieces/Mushroom/toadstool4%groundpieces/ground/mushroom/toadstool4%g
s%global/GroundPieces/Rock/fish%groundpieces/ground/real/fish%g
s%global/GroundPieces/Rock/granit1%groundpieces/solid/rock/granit1%g
s%global/GroundPieces/Rock/granit2%groundpieces/solid/rock/granit2%g
s%global/GroundPieces/Rock/granit3%groundpieces/solid/rock/granit3%g
s%global/GroundPieces/Rock/granit4%groundpieces/solid/rock/granit4%g
s%global/GroundPieces/Rock/granit5%groundpieces/solid/rock/granit5%g
s%global/GroundPieces/Rock/granit6%groundpieces/solid/rock/granit6%g
s%global/GroundPieces/Rock/green1%groundpieces/ground/real/green1%g
s%global/GroundPieces/Rock/green2%groundpieces/ground/real/green2%g
s%global/GroundPieces/Rock/real1%groundpieces/ground/real/real1%g
s%global/GroundPieces/Rock/real10%groundpieces/ground/real/real10%g
s%global/GroundPieces/Rock/real11%groundpieces/ground/real/real11%g
s%global/GroundPieces/Rock/real12%groundpieces/ground/real/real12%g
s%global/GroundPieces/Rock/real13%groundpieces/ground/real/real13%g
s%global/GroundPieces/Rock/real14%groundpieces/ground/real/real14%g
s%global/GroundPieces/Rock/real15%groundpieces/ground/real/real15%g
s%global/GroundPieces/Rock/real16%groundpieces/ground/real/real16%g
s%global/GroundPieces/Rock/real17%groundpieces/ground/real/real17%g
s%global/GroundPieces/Rock/real18%groundpieces/ground/real/real18%g
s%global/GroundPieces/Rock/real19%groundpieces/ground/real/real19%g
s%global/GroundPieces/Rock/real2%groundpieces/ground/real/real2%g
s%global/GroundPieces/Rock/real20%groundpieces/ground/real/real20%g
s%global/GroundPieces/Rock/real21%groundpieces/ground/real/real21%g
s%global/GroundPieces/Rock/real22%groundpieces/ground/real/real22%g
s%global/GroundPieces/Rock/real23%groundpieces/ground/real/real23%g
s%global/GroundPieces/Rock/real24%groundpieces/ground/real/real24%g
s%global/GroundPieces/Rock/real25%groundpieces/ground/real/real25%g
s%global/GroundPieces/Rock/real26%groundpieces/ground/real/real26%g
s%global/GroundPieces/Rock/real27%groundpieces/ground/real/real27%g
s%global/GroundPieces/Rock/real28%groundpieces/ground/real/real28%g
s%global/GroundPieces/Rock/real29%groundpieces/ground/real/real29%g
s%global/GroundPieces/Rock/real3%groundpieces/ground/real/real3%g
s%global/GroundPieces/Rock/real30%groundpieces/ground/real/real30%g
s%global/GroundPieces/Rock/real31%groundpieces/ground/rock/blackrock1%g
s%global/GroundPieces/Rock/real32%groundpieces/ground/rock/blackrock2%g
s%global/GroundPieces/Rock/real33%groundpieces/ground/rock/blackrock3%g
s%global/GroundPieces/Rock/real34%groundpieces/ground/rock/blackrock4%g
s%global/GroundPieces/Rock/real35%groundpieces/ground/real/real35%g
s%global/GroundPieces/Rock/real36%groundpieces/ground/real/real36%g
s%global/GroundPieces/Rock/real37%groundpieces/ground/real/real37%g
s%global/GroundPieces/Rock/real4%groundpieces/ground/real/real4%g
s%global/GroundPieces/Rock/real5%groundpieces/ground/real/real5%g
s%global/GroundPieces/Rock/real6%groundpieces/ground/real/real6%g
s%global/GroundPieces/Rock/real7%groundpieces/ground/real/real7%g
s%global/GroundPieces/Rock/real8%groundpieces/ground/real/real8%g
s%global/GroundPieces/Rock/real9%groundpieces/ground/real/real9%g
s%global/GroundPieces/Rock/rock1%groundpieces/ground/foliage/rock1%g
s%global/GroundPieces/Rock/rock2%groundpieces/ground/foliage/rock2%g
s%global/GroundPieces/Rock/rock3%groundpieces/ground/foliage/rock3%g
s%global/GroundPieces/Rock/rock4%groundpieces/ground/foliage/rock4%g
s%global/GroundPieces/Rock/rock5%groundpieces/ground/foliage/rock5%g
s%global/GroundPieces/Rock/rock6%groundpieces/ground/foliage/rock6%g
s%global/GroundPieces/Snow/gpiece1%groundpieces/ground/snow/gpiece1%g
s%global/GroundPieces/Snow/ice1%groundpieces/ground/snow/ice1%g
s%global/GroundPieces/Snow/ice2%groundpieces/ground/snow/ice2%g
s%global/GroundPieces/Snow/igloo%groundpieces/ground/snow/igloo%g
s%global/GroundPieces/Snow/piece1%groundpieces/ground/snow/piece1%g
s%global/GroundPieces/Snow/piece2%groundpieces/ground/snow/piece2%g
s%global/GroundPieces/Snow/piece3%groundpieces/ground/snow/piece3%g
s%global/GroundPieces/Snow/slopedr%groundpieces/ground/snow/slopedr%g
s%global/GroundPieces/Snow/snowman%groundpieces/ground/snow/snowman%g
s%global/GroundPieces/Snow/xmas-tree%groundpieces/ground/snow/xmas-tree%g
s%global/GroundPieces/Sortie/column1%groundpieces/ground/sortie/column%g
s%global/GroundPieces/Sortie/column2%groundpieces/ground/sortie/column2%g
s%global/GroundPieces/Sortie/column3%groundpieces/ground/sortie/column3%g
s%global/GroundPieces/Sortie/plate_forme%groundpieces/ground/sortie/plate_forme%g
s%global/GroundPieces/Sortie/plate_forme_left%groundpieces/ground/sortie/plate_forme_left%g
s%global/GroundPieces/Sortie/plate_forme_right%groundpieces/ground/sortie/plate_forme_right%g
s%global/GroundPieces/Space/block1%groundpieces/ground/space/block1%g
s%global/GroundPieces/Space/diagonal%groundpieces/ground/space/diagonal%g
s%global/GroundPieces/Space/diagonalr%groundpieces/ground/space/diagonalr%g
s%global/GroundPieces/Space/grid1%groundpieces/bridge/space/grid1%g
s%global/GroundPieces/Space/grid2%groundpieces/bridge/space/grid2%g
s%global/GroundPieces/Space/grid3%groundpieces/bridge/space/grid3%g
s%global/GroundPieces/Space/smallblock1%groundpieces/ground/space/smallblock1%g
s%global/GroundPieces/Space/smallblock2%groundpieces/ground/space/smallblock2%g
s%global/GroundPieces/Space/smallblock3%groundpieces/ground/space/smallblock3%g
s%global/GroundPieces/Space/smalltower%groundpieces/ground/space/smalltower%g
s%global/GroundPieces/Space/tower1%groundpieces/ground/space/tower1%g
s%global/GroundPieces/Space/way%groundpieces/ground/space/way%g
s%global/GroundPieces/Sweets/allsort1%groundpieces/ground/sweets/allsort1%g
s%global/GroundPieces/Sweets/allsort2%groundpieces/ground/sweets/allsort2%g
s%global/GroundPieces/Sweets/aquachoc%groundpieces/ground/sweets/aquachoc%g
s%global/GroundPieces/Sweets/cake1%groundpieces/ground/sweets/cake1%g
s%global/GroundPieces/Sweets/cake2%groundpieces/ground/sweets/cake2%g
s%global/GroundPieces/Sweets/cake3%groundpieces/ground/sweets/cake3%g
s%global/GroundPieces/Sweets/cake4%groundpieces/ground/sweets/cake4%g
s%global/GroundPieces/Sweets/cake5%groundpieces/ground/sweets/cake5%g
s%global/GroundPieces/Sweets/canestalk%groundpieces/ground/sweets/canestalk%g
s%global/GroundPieces/Sweets/canestub%groundpieces/ground/sweets/canestub%g
s%global/GroundPieces/Sweets/canetop%groundpieces/ground/sweets/canetop%g
s%global/GroundPieces/Sweets/chocbar%groundpieces/ground/sweets/chocbar%g
s%global/GroundPieces/Sweets/chocbloc%groundpieces/ground/sweets/chocbloc%g
s%global/GroundPieces/Sweets/chocbloc-lowleft%groundpieces/ground/sweets/chocbloc-lowleft%g
s%global/GroundPieces/Sweets/chocbloc-lowright%groundpieces/ground/sweets/chocbloc-lowright%g
s%global/GroundPieces/Sweets/chocbloc-topleft%groundpieces/ground/sweets/chocbloc-topleft%g
s%global/GroundPieces/Sweets/chocbloc-topright%groundpieces/ground/sweets/chocbloc-topright%g
s%global/GroundPieces/Sweets/goldchoc%groundpieces/ground/sweets/goldchoc%g
s%global/GroundPieces/Sweets/greenjellybaby%groundpieces/ground/sweets/greenjellybaby%g
s%global/GroundPieces/Sweets/icecream%groundpieces/ground/sweets/icecream%g
s%global/GroundPieces/Sweets/jellybaby%groundpieces/ground/sweets/greenjellybaby%g
s%global/GroundPieces/Sweets/jellybaby2%groundpieces/ground/sweets/redjellybaby%g
s%global/GroundPieces/Sweets/jube1%groundpieces/ground/sweets/jube1%g
s%global/GroundPieces/Sweets/jube2%groundpieces/ground/sweets/jube2%g
s%global/GroundPieces/Sweets/lollipop%groundpieces/ground/sweets/lollipop%g
s%global/GroundPieces/Sweets/lollipop-purp%groundpieces/ground/sweets/lollipop-purp%g
s%global/GroundPieces/Sweets/mmblue%groundpieces/ground/sweets/mmblue%g
s%global/GroundPieces/Sweets/mmbrown%groundpieces/ground/sweets/mmbrown%g
s%global/GroundPieces/Sweets/mmred%groundpieces/ground/sweets/mmred%g
s%global/GroundPieces/Sweets/mmyellow%groundpieces/ground/sweets/mmyellow%g
s%global/GroundPieces/Sweets/purpchoc%groundpieces/ground/sweets/purpchoc%g
s%global/GroundPieces/Sweets/purplechoc%groundpieces/ground/sweets/purplechoc%g
s%global/GroundPieces/Sweets/redjellybaby%groundpieces/ground/sweets/redjellybaby%g
s%global/GroundPieces/Test/test1%groundpieces/ground/test/test1%g
s%global/GroundPieces/Test/test2%groundpieces/ground/test/test2%g
s%global/GroundPieces/Test/test3%groundpieces/ground/test/test3%g
s%global/GroundPieces/Test/test4%groundpieces/ground/test/test4%g
s%global/GroundPieces/Test/test5%groundpieces/ground/test/test5%g
s%global/GroundPieces/Test/test6%groundpieces/ground/test/test6%g
s%global/GroundPieces/bpice1%groundpieces/ground/misc/bpiece1%g
s%global/GroundPieces/bpice2%groundpieces/ground/misc/bpiece2%g
s%global/GroundPieces/bpice3%groundpieces/ground/misc/bpiece3%g
s%global/GroundPieces/bpice4%groundpieces/ground/misc/bpiece4%g
s%global/GroundPieces/bpice5%groundpieces/ground/misc/bpiece5%g
s%global/GroundPieces/bpice6%groundpieces/ground/misc/bpiece6%g
s%global/GroundPieces/bpiece1%groundpieces/ground/misc/bpiece1%g
s%global/GroundPieces/bpiece2%groundpieces/ground/misc/bpiece2%g
s%global/GroundPieces/bpiece3%groundpieces/ground/misc/bpiece3%g
s%global/GroundPieces/bpiece4%groundpieces/ground/misc/bpiece4%g
s%global/GroundPieces/bpiece5%groundpieces/ground/misc/bpiece5%g
s%global/GroundPieces/bpiece6%groundpieces/ground/misc/bpiece6%g
s%global/GroundPieces/cable1%groundpieces/ground/ordina/cable1%g
s%global/GroundPieces/cable2%groundpieces/ground/ordina/cable2%g
s%global/GroundPieces/cdrom1%groundpieces/ground/ordina/cdrom1%g
s%global/GroundPieces/clavier1%groundpieces/ground/ordina/clavier1%g
s%global/GroundPieces/cpu1%groundpieces/ground/ordina/cpu1%g
s%global/GroundPieces/ecran%groundpieces/ground/ordina/ecran%g
s%global/GroundPieces/green1%groundpieces/ground/misc/green1%g
s%global/GroundPieces/green2%groundpieces/ground/misc/green2%g
s%global/GroundPieces/pice1%groundpieces/ground/misc/grey_stone1%g
s%global/GroundPieces/pice2%groundpieces/ground/misc/grey_stone2%g
s%global/GroundPieces/pice3%groundpieces/ground/misc/grey_stone3%g
s%global/GroundPieces/pice4%groundpieces/ground/misc/grey_stone4%g
s%global/GroundPieces/pice5%groundpieces/ground/misc/grey_stone5%g
s%global/GroundPieces/piece1%groundpieces/ground/misc/grey_stone1%g
s%global/GroundPieces/piece2%groundpieces/ground/misc/grey_stone2%g
s%global/GroundPieces/piece3%groundpieces/ground/misc/grey_stone3%g
s%global/GroundPieces/piece4%groundpieces/ground/misc/grey_stone4%g
s%global/GroundPieces/piece5%groundpieces/ground/misc/grey_stone5%g
s%global/GroundPieces/pipe_dl%groundpieces/ground/industrial/pipe_bl%g
s%global/GroundPieces/pipe_dr%groundpieces/ground/industrial/pipe_br%g
s%global/GroundPieces/pipe_h%groundpieces/ground/industrial/pipe1%g
s%global/GroundPieces/pipe_ph%groundpieces/ground/industrial/pipe4%g
s%global/GroundPieces/pipe_pv%groundpieces/ground/industrial/pipe5%g
s%global/GroundPieces/pipe_ul%groundpieces/ground/industrial/pipe_ul%g
s%global/GroundPieces/pipe_ur%groundpieces/ground/industrial/pipe_ur%g
s%global/GroundPieces/pipe_v%groundpieces/ground/industrial/pipe2%g
s%global/GroundPieces/sol1%groundpieces/ground/ordina/sol2%g
s%global/GroundPieces/sol2%groundpieces/ground/ordina/sol3%g
s%global/GroundPieces/sol3%groundpieces/ground/ordina/sol4%g
s%global/Gunge/gunge1%groundpieces/transparent/industrial/gunge1%g
s%global/Gunge/gunge10%groundpieces/transparent/industrial/gunge10%g
s%global/Gunge/gunge11%groundpieces/transparent/industrial/gunge11%g
s%global/Gunge/gunge12%groundpieces/transparent/industrial/gunge12%g
s%global/Gunge/gunge13%groundpieces/transparent/industrial/gunge13%g
s%global/Gunge/gunge14%groundpieces/transparent/industrial/gunge14%g
s%global/Gunge/gunge15%groundpieces/transparent/industrial/gunge15%g
s%global/Gunge/gunge2%groundpieces/transparent/industrial/gunge2%g
s%global/Gunge/gunge3%groundpieces/transparent/industrial/gunge3%g
s%global/Gunge/gunge4%groundpieces/transparent/industrial/gunge4%g
s%global/Gunge/gunge5%groundpieces/transparent/industrial/gunge5%g
s%global/Gunge/gunge6%groundpieces/transparent/industrial/gunge6%g
s%global/Gunge/gunge7%groundpieces/transparent/industrial/gunge7%g
s%global/Gunge/gunge8%groundpieces/transparent/industrial/gunge8%g
s%global/Gunge/gunge9%groundpieces/transparent/industrial/gunge9%g
s%global/Hotspots/cabin%groundpieces/ground/snow/cabin%g
s%global/Hotspots/cabin_winter%groundpieces/ground/snow/cabin_winter%g
s%global/Hotspots/colum%groundpieces/ground/misc/column%g
s%global/Hotspots/colum_flat%groundpieces/ground/misc/column_flat%g
s%global/Hotspots/colum_pice1%groundpieces/ground/desert/column_piece1%g
s%global/Hotspots/colum_pice2%groundpieces/ground/desert/column_piece2%g
s%global/Hotspots/colum_pice3%groundpieces/ground/desert/column_piece3%g
s%global/Hotspots/colum_piece1%groundpieces/ground/desert/column_piece1%g
s%global/Hotspots/colum_piece2%groundpieces/ground/desert/column_piece2%g
s%global/Hotspots/colum_piece3%groundpieces/ground/desert/column_piece3%g
s%global/Hotspots/danger%groundpieces/ground/signposts/danger%g
s%global/Hotspots/down_arrow%groundpieces/ground/signposts/arrow_down%g
s%global/Hotspots/dragon%groundpieces/ground/misc/dragon%g
s%global/Hotspots/engine%hotspots/space/engine%g
s%global/Hotspots/left_arrow%groundpieces/ground/signposts/arrow_left%g
s%global/Hotspots/pillar1%groundpieces/ground/desert/pillar1%g
s%global/Hotspots/pillar2%groundpieces/ground/desert/pillar2%g
s%global/Hotspots/pillar3%groundpieces/ground/desert/pillar3%g
s%global/Hotspots/plate%groundpieces/solid/misc/metalplate_horiz%g
s%global/Hotspots/plate2%groundpieces/solid/misc/metalplate_large%g
s%global/Hotspots/plate_small%groundpieces/solid/misc/metalplate_small%g
s%global/Hotspots/right_arrow%groundpieces/ground/signposts/arrow_right%g
s%global/Hotspots/signposts/basher%hotspots/signposts/basher%g
s%global/Hotspots/signposts/blocker%hotspots/signposts/blocker%g
s%global/Hotspots/signposts/bomber%hotspots/signposts/bomber%g
s%global/Hotspots/signposts/bridger%hotspots/signposts/bridger%g
s%global/Hotspots/signposts/climber%hotspots/signposts/climber%g
s%global/Hotspots/signposts/digger%hotspots/signposts/digger%g
s%global/Hotspots/signposts/e%hotspots/signposts/arrow_east%g
s%global/Hotspots/signposts/floater%hotspots/signposts/floater%g
s%global/Hotspots/signposts/miner%hotspots/signposts/miner%g
s%global/Hotspots/signposts/nogo%hotspots/signposts/nogo%g
s%global/Hotspots/signposts/w%hotspots/signposts/arrow_west%g
s%global/Hotspots/stone0%groundpieces/ground/misc/stone0%g
s%global/Hotspots/stone1%groundpieces/ground/misc/stone1%g
s%global/Hotspots/stone2%groundpieces/ground/misc/stone2%g
s%global/Hotspots/up_arrow%groundpieces/ground/signposts/arrow_up%g
s%global/Hotspots/well%groundpieces/ground/misc/well%g
s%global/Industrial/Gunge/gunge1%groundpieces/transparent/industrial/gunge1%g
s%global/Industrial/Gunge/gunge10%groundpieces/transparent/industrial/gunge10%g
s%global/Industrial/Gunge/gunge11%groundpieces/transparent/industrial/gunge11%g
s%global/Industrial/Gunge/gunge12%groundpieces/transparent/industrial/gunge12%g
s%global/Industrial/Gunge/gunge13%groundpieces/transparent/industrial/gunge13%g
s%global/Industrial/Gunge/gunge14%groundpieces/transparent/industrial/gunge14%g
s%global/Industrial/Gunge/gunge15%groundpieces/transparent/industrial/gunge15%g
s%global/Industrial/Gunge/gunge2%groundpieces/transparent/industrial/gunge2%g
s%global/Industrial/Gunge/gunge3%groundpieces/transparent/industrial/gunge3%g
s%global/Industrial/Gunge/gunge4%groundpieces/transparent/industrial/gunge4%g
s%global/Industrial/Gunge/gunge5%groundpieces/transparent/industrial/gunge5%g
s%global/Industrial/Gunge/gunge6%groundpieces/transparent/industrial/gunge6%g
s%global/Industrial/Gunge/gunge7%groundpieces/transparent/industrial/gunge7%g
s%global/Industrial/Gunge/gunge8%groundpieces/transparent/industrial/gunge8%g
s%global/Industrial/Gunge/gunge9%groundpieces/transparent/industrial/gunge9%g
s%global/Industrial/greybri1%groundpieces/solid/industrial/greybri1%g
s%global/Industrial/greybri2%groundpieces/solid/industrial/greybri2%g
s%global/Industrial/greybri3%groundpieces/solid/industrial/greybri3%g
s%global/Industrial/greybri5%groundpieces/solid/industrial/greybri5%g
s%global/Industrial/joint1%groundpieces/solid/industrial/joint1%g
s%global/Industrial/joint2%groundpieces/solid/industrial/joint2%g
s%global/Industrial/joint3%groundpieces/solid/industrial/joint3%g
s%global/Industrial/joint4%groundpieces/solid/industrial/joint4%g
s%global/Industrial/joint5%groundpieces/solid/industrial/joint5%g
s%global/Industrial/pipe_dl%groundpieces/ground/industrial/pipe_bl%g
s%global/Industrial/pipe_dr%groundpieces/ground/industrial/pipe_br%g
s%global/Industrial/pipe_h%groundpieces/ground/industrial/pipe1%g
s%global/Industrial/pipe_ph%groundpieces/ground/industrial/pipe4%g
s%global/Industrial/pipe_pv%groundpieces/ground/industrial/pipe5%g
s%global/Industrial/pipe_ul%groundpieces/ground/industrial/pipe_ul%g
s%global/Industrial/pipe_ur%groundpieces/ground/industrial/pipe_ur%g
s%global/Industrial/pipe_v%groundpieces/ground/industrial/pipe2%g
s%global/Industrial/rivet%groundpieces/solid/industrial/rivet%g
s%global/Industrial/screw%groundpieces/solid/industrial/screw%g
s%global/Industrial/steel1%groundpieces/solid/industrial/steel1%g
s%global/Industrial/steel2%groundpieces/solid/industrial/steel2%g
s%global/Industrial/steel3%groundpieces/solid/industrial/steel3%g
s%global/Industrial/steel4%groundpieces/solid/industrial/steel4%g
s%global/Industrial/steel5%groundpieces/solid/industrial/steel5%g
s%global/Industrial/weld1%groundpieces/solid/industrial/weld1%g
s%global/Industrial/weld2%groundpieces/solid/industrial/weld2%g
s%global/Industrial/weld3%groundpieces/solid/industrial/weld3%g
s%global/Industrial/weld4%groundpieces/solid/industrial/weld4%g
s%global/Industrial/weld5%groundpieces/solid/industrial/weld5%g
s%global/Industrial/weld6%groundpieces/solid/industrial/weld6%g
s%global/Industrial/weld7%groundpieces/solid/industrial/weld7%g
s%global/Liquid/lava%liquids/lava%g
s%global/Liquid/slime%liquids/slime%g
s%global/Liquid/swater%liquids/swater%g
s%global/Liquid/water%liquids/water%g
s%global/Liquid/water2%liquids/water2%g
s%global/Liquid/water3%liquids/water3%g
s%global/Liquid/water4%liquids/water4%g
s%global/Liquid/water5%liquids/water3%g
s%global/Steel/steel1%groundpieces/solid/industrial/steel1%g
s%global/Steel/steel2%groundpieces/solid/industrial/steel2%g
s%global/Steel/steel3%groundpieces/solid/industrial/steel3%g
s%global/Steel/steel4%groundpieces/solid/industrial/steel4%g
s%global/Steel/steel5%groundpieces/solid/industrial/steel5%g
s%global/Ywlam/bigdimwall%hotspots/desert/bigdimwall%g
s%global/Ywlam/bigsand%groundpieces/ground/desert/bigsand%g
s%global/Ywlam/blinky%special/pacman/blinky%g
s%global/Ywlam/clyde%special/pacman/clyde%g
s%global/Ywlam/inky%special/pacman/inky%g
s%global/Ywlam/leftsmallbrick%groundpieces/ground/desert/leftsmallbrick%g
s%global/Ywlam/leftsmallsand%groundpieces/ground/desert/leftsmallsand%g
s%global/Ywlam/mediumdimwall%hotspots/desert/mediumdimwall%g
s%global/Ywlam/mediumegpytpict%hotspots/desert/mediumegyptpic%g
s%global/Ywlam/mediummummy%hotspots/desert/mediummummy%g
s%global/Ywlam/mediumsand%groundpieces/ground/desert/mediumsand%g
s%global/Ywlam/mediumsphinx%hotspots/desert/mediumsphinx%g
s%global/Ywlam/pacbkg%special/pacman/pacman-bkg%g
s%global/Ywlam/pacframe%special/pacman/pacman-frame%g
s%global/Ywlam/pacman%special/pacman/pacman%g
s%global/Ywlam/pacmaze%special/pacman/pacman-maze%g
s%global/Ywlam/pinky%special/pacman/pinky%g
s%global/Ywlam/rightsmallbrick%groundpieces/ground/desert/rightsmallbrick%g
s%global/Ywlam/rightsmallsand%groundpieces/ground/desert/rightsmallsand%g
s%global/Ywlam/smallD%hotspots/desert/smallD%g
s%global/Ywlam/smallE%hotspots/desert/smallE%g
s%global/Ywlam/smallG%hotspots/desert/smallG%g
s%global/Ywlam/smallO%hotspots/desert/smallO%g
s%global/Ywlam/smalldimwall%hotspots/desert/smalldimwall%g
s%global/Ywlam/smallegpytpict%hotspots/desert/smallegyptpic%g
s%global/Ywlam/smallsand%groundpieces/ground/desert/smallsand%g
s%global/Ywlam/smallsphinx%hotspots/desert/smallsphinx%g
s%hotspots/Signposts/arrow_east%hotspots/signposts/arrow_east%g
s%hotspots/Signposts/arrow_south%hotspots/signposts/arrow_south%g
s%hotspots/Signposts/arrow_west%hotspots/signposts/arrow_west%g
s%liquids/Liquid/lava%liquids/lava%g
s%liquids/Liquid/slime%liquids/slime%g
s%liquids/Liquid/swater%liquids/swater%g
s%liquids/Liquid/water%liquids/water%g
s%liquids/Liquid/water2%liquids/water2%g
s%liquids/Liquid/water3%liquids/water3%g
s%liquids/Liquid/water4%liquids/water4%g
s%liquids/Liquid/water5%liquids/water5%g
s%liquids/Liquid/water_cmap%liquids/water_cmap%g
s%liquids/liquid/lava%liquids/lava%g
s%liquids/liquid/slime%liquids/slime%g
s%liquids/liquid/swater%liquids/swater%g
s%liquids/liquid/water%liquids/water%g
s%liquids/liquid/water2%liquids/water2%g
s%liquids/liquid/water3%liquids/water3%g
s%liquids/liquid/water4%liquids/water4%g
s%liquids/liquid/water5%liquids/water5%g
s%liquids/liquid/water_cmap%liquids/water_cmap%g
s%pingus/Particles/explosive%particles/explosive%g
s%pingus/Particles/ground%particles/ground%g
s%pingus/Particles/ground_snow%particles/ground_snow%g
s%pingus/Particles/pingu_explo%particles/pingu_explo%g
s%pingus/Particles/rain1%particles/rain1%g
s%pingus/Particles/rain2%particles/rain2%g
s%pingus/Particles/rain_splash%particles/rain_splash%g
s%pingus/Particles/smoke%particles/smoke%g
s%pingus/Particles/smoke2%particles/smoke2%g
s%pingus/Particles/snow1%particles/snow1%g
s%pingus/Particles/snow2%particles/snow2%g
s%pingus/Particles/snow3%particles/snow3%g
s%pingus/Particles/snow4%particles/snow4%g
s%pingus/Particles/snow5%particles/snow5%g
s%pingus/particles/explosive%particles/explosive%g
s%pingus/particles/ground%particles/ground%g
s%pingus/particles/ground_snow%particles/ground_snow%g
s%pingus/particles/pingu_explo%particles/pingu_explo%g
s%pingus/particles/rain1%particles/rain1%g
s%pingus/particles/rain2%particles/rain2%g
s%pingus/particles/rain_splash%particles/rain_splash%g
s%pingus/particles/smoke%particles/smoke%g
s%pingus/particles/smoke2%particles/smoke2%g
s%pingus/particles/snow1%particles/snow1%g
s%pingus/particles/snow2%particles/snow2%g
s%pingus/particles/snow3%particles/snow3%g
s%pingus/particles/snow4%particles/snow4%g
s%pingus/particles/snow5%particles/snow5%g
s%textures/Textures/anim_fire%textures/anim_fire%g
s%textures/Textures/blueflame%textures/blueflame%g
s%textures/Textures/bwsortiebg%textures/bwsortiebg%g
s%textures/Textures/clouds%textures/clouds%g
s%textures/Textures/clouds2%textures/clouds2%g
s%textures/Textures/clouds3%textures/clouds3%g
s%textures/Textures/creepers%textures/creepers%g
s%textures/Textures/creepers-mirrored%textures/creepers-mirrored%g
s%textures/Textures/crystal%textures/crystal%g
s%textures/Textures/cyanspace%textures/cyanspace%g
s%textures/Textures/darkjungle%textures/darkjungle%g
s%textures/Textures/default%textures/default%g
s%textures/Textures/desert%textures/desert%g
s%textures/Textures/desert_room%textures/desert_room%g
s%textures/Textures/enchantedjungle%textures/enchantedjungle%g
s%textures/Textures/flame%textures/flame%g
s%textures/Textures/fond1%textures/fond1%g
s%textures/Textures/fruitcaketile%textures/fruitcaketile%g
s%textures/Textures/green_tendrils%textures/green_tendrils%g
s%textures/Textures/greentex%textures/greentex%g
s%textures/Textures/happyclouds%textures/happyclouds%g
s%textures/Textures/icetile%textures/icetile%g
s%textures/Textures/industrial%textures/industrial%g
s%textures/Textures/latejungle%textures/latejungle%g
s%textures/Textures/lunartile%textures/lunartile%g
s%textures/Textures/mountain%textures/mountain%g
s%textures/Textures/nightjungle%textures/nightjungle%g
s%textures/Textures/ordina%textures/ordina%g
s%textures/Textures/rock6%textures/rock6%g
s%textures/Textures/rockagglo%textures/rockagglo%g
s%textures/Textures/rocktile%textures/rocktile%g
s%textures/Textures/rooftile%textures/rooftile%g
s%textures/Textures/rooftile2%textures/rooftile2%g
s%textures/Textures/sortie%textures/sortie%g
s%textures/Textures/stars%textures/stars%g
s%textures/Textures/stone%textures/stone%g
s%textures/Textures/stones%textures/stones%g
s%textures/Textures/swirljungle%textures/swirljungle%g
s%textures/Textures/thunderstorm%textures/thunderstorm%g
s%textures/textures/anim_fire%textures/anim_fire%g
s%textures/textures/blueflame%textures/blueflame%g
s%textures/textures/bwsortiebg%textures/bwsortiebg%g
s%textures/textures/clouds%textures/clouds%g
s%textures/textures/clouds2%textures/clouds2%g
s%textures/textures/clouds3%textures/clouds3%g
s%textures/textures/creepers%textures/creepers%g
s%textures/textures/creepers-mirrored%textures/creepers-mirrored%g
s%textures/textures/crystal%textures/crystal%g
s%textures/textures/cyanspace%textures/cyanspace%g
s%textures/textures/darkjungle%textures/darkjungle%g
s%textures/textures/default%textures/default%g
s%textures/textures/desert%textures/desert%g
s%textures/textures/desert_room%textures/desert_room%g
s%textures/textures/enchantedjungle%textures/enchantedjungle%g
s%textures/textures/flame%textures/flame%g
s%textures/textures/fond1%textures/fond1%g
s%textures/textures/fruitcaketile%textures/fruitcaketile%g
s%textures/textures/green_tendrils%textures/green_tendrils%g
s%textures/textures/greentex%textures/greentex%g
s%textures/textures/happyclouds%textures/happyclouds%g
s%textures/textures/icetile%textures/icetile%g
s%textures/textures/industrial%textures/industrial%g
s%textures/textures/latejungle%textures/latejungle%g
s%textures/textures/lunartile%textures/lunartile%g
s%textures/textures/mountain%textures/mountain%g
s%textures/textures/nightjungle%textures/nightjungle%g
s%textures/textures/ordina%textures/ordina%g
s%textures/textures/rock6%textures/rock6%g
s%textures/textures/rockagglo%textures/rockagglo%g
s%textures/textures/rocktile%textures/rocktile%g
s%textures/textures/rooftile%textures/rooftile%g
s%textures/textures/rooftile2%textures/rooftile2%g
s%textures/textures/sortie%textures/sortie%g
s%textures/textures/stars%textures/stars%g
s%textures/textures/stone%textures/stone%g
s%textures/textures/stones%textures/stones%g
s%textures/textures/swirljungle%textures/swirljungle%g
s%textures/textures/thunderstorm%textures/thunderstorm%g
