;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/basher-tutorial-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "If the way is blocked, bash away")
    (description "Similar to the Digger action that you already know from previous levels, "
                 "there is also an action that allows the Pingus to dig horizontally, as opposed "
                 "to the vertical dig ability the Digger action provides. This new action is "
                 "called Basher. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 20)
    (number-to-save 10)
    (time -1)
    (difficulty 40)
    (playable 1)
    (comment )
    (music "pingus-6.it")
    (actions 
      (basher 10))
    (levelsize 1900 700))
  (objects 
    (surface-background 
      (surface 
        (image "textures/blueflame")
        (modifier "ROT0"))
      (color 0 0 0 0.5)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 73.5 96.5 -150))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 197.828 110.072 -50)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 541 349 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/iceblock1")
        (modifier "ROT0"))
      (position 95 181 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 167 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 100 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 88 261 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 231 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/iceblock1")
        (modifier "ROT0"))
      (position 579 199 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90"))
      (position 1013 269 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/iceblock1")
        (modifier "ROT180FLIP"))
      (position 605 280 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/iceblock1")
        (modifier "ROT180FLIP"))
      (position 527 276 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 284 407 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 353 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 200 335 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 912 395 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 244 376 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 518 402 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 602 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 677 397 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 312 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 611 351 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 647 506 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 621 441 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 464 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 784 396 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 623 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 696 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90"))
      (position 958 470 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 294 332 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 313 467 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 349 535 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 382 602 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0FLIP"))
      (position 654 572 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 458 547 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 746 639 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90FLIP"))
      (position 274 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90FLIP"))
      (position 337 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 262 257 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 211 259 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 539 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 650 356 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 763 394 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 868 400 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1445 447 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1361 452 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1275 469 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 438 350 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 895 402 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 1049 438 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 299 336 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 396 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 727 528 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 393 441 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 385 625 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1597 464 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 465 614 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1669 463 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 765 596 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1499 438 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1338 452 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone6")
        (modifier "ROT0"))
      (position 647 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 483 653 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT0"))
      (position 638 597 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/grey_stone4")
        (modifier "ROT180FLIP"))
      (position 517 562 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 600 560 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 746 591 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 456 616 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 1022 284 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 565 622 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 1022 257 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1011 303 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 938 395 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 971 397 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 169 340 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 1338 392 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 269 439 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90"))
      (position 1016 428 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 313 601 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 569 626 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 571 562 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1529 456 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 992 514 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1032 507 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1018 311 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/iceblock1")
        (modifier "ROT180FLIP"))
      (position 1325 302 0))
    (hotspot 
      (surface 
        (image "hotspots/signposts/basher")
        (modifier "ROT0"))
      (position 472.5 299.5 0)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 939 404 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 1544 391 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT180FLIP"))
      (position 1070 383 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1089 400 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1144 399 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1203 393 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1264 383 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1260 392 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 1485 393 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1316 390 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 981 384 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1079 405 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1183 402 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1352 389 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1086 551 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1194 470 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1157 508 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 1411 391 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1415 389 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 1574 391 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90"))
      (position 1740 232 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 1748 236 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 1748 209 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1737 255 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1744 263 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1275 390 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1293 377 0))
    (exit 
      (owner-id 0)
      (position 1676.5 394.5 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1360 377 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1425 451 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1604 461 0))
    (entrance 
      (position 241.563 147.857 0)
      (type "generic")
      (direction "right")
      (release-rate 80)
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 108 260 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 139 259 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 88 261 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 168 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 140 263 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 683 346 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1020 389 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 1022 398 0))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 197.381 110.255 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
