;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/digger-tutorial2-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Learning to dig")
    (description "This is your first mission. As always, it's pretty easy. All you have to "
                 "do is to give a Pingu the command to dig a hole into the ground so that they "
                 "can reach the exit. This can be accomplished simply by clicking on a Pingu. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 10)
    (number-to-save 5)
    (time -1)
    (difficulty 0)
    (playable 1)
    (comment "first level for the story mode, tutorial island")
    (music "pingus-7.it")
    (actions 
      (digger 10))
    (levelsize 1400 700))
  (objects 
    (surface-background 
      (surface 
        (image "textures/clouds2")
        (modifier "ROT0"))
      (color 0.1 0 0 0.3)
      (scroll-x -1.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 0 0 -150))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -19.52 629 -50)
      (repeat 23)
      (speed 55))
    (hotspot 
      (surface 
        (image "hotspots/signposts/digger")
        (modifier "ROT0"))
      (position 796.28 302.92 -50)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/signposts/arrow_south")
        (modifier "ROT0"))
      (position 760.28 301.92 -50)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 469.411 170.769 -50)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 305 351 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 267 379 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 653 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90"))
      (position 373 362 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone7")
        (modifier "ROT0"))
      (position 332 260 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90FLIP"))
      (position 288 317 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone7")
        (modifier "ROT0"))
      (position 298 297 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone7")
        (modifier "ROT0"))
      (position 366 305 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone7")
        (modifier "ROT0"))
      (position 880 260 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 318 535 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 500 534 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 217 483 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 657 535 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 844 484 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180"))
      (position 498 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone7")
        (modifier "ROT0"))
      (position 914 305 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/misc/stone7")
        (modifier "ROT0"))
      (position 846 297 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 286 482 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 779 343 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 883 362 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT90FLIP"))
      (position 872 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 337 340 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 896 437 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 441 533 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 548 533 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 713 533 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 305 339 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 405 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 570 344 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 730 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 893 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 952 357 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 311 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 842 347 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 447 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 244 429 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 178 537 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 446 540 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 593 539 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 796 538 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 578 350 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 737 348 0))
    (exit 
      (owner-id 0)
      (position 810.48 535.52 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 392 579 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 350 578 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 733 571 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 492 560 0))
    (entrance 
      (position 516.494 210.525 0)
      (type "generic")
      (direction "right")
      (release-rate 150)
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 110 599 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 1056 590 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 493 614 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 851 623 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 866 563 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 923 492 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 251 584 0))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -49.52 643 50)
      (repeat 23)
      (speed 60))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 469.6 170.896 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
