;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/jumper-tutorial-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Jump for joy")
    (description "Sometimes a Pingu needs to reach a platform that is far away, but not reachable "
                 "by walking. That's when the Jumper comes in handy - it allows the Pingu to "
                 "make a small jump and so enables him to reach the platform. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 25)
    (number-to-save 5)
    (time -1)
    (difficulty 5)
    (playable 1)
    (comment )
    (music "pingus-5.it")
    (actions 
      (jumper 80))
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/happyclouds")
        (modifier "ROT0"))
      (color 0 0 0 0.3)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 4 5 -150))
    (hotspot 
      (surface 
        (image "hotspots/signposts/arrow_northeast")
        (modifier "ROT0"))
      (position 464.319 210.65 -50)
      (speed -1)
      (parallax 1))
    (hotspot 
      (surface 
        (image "hotspots/signposts/arrow_northeast")
        (modifier "ROT0"))
      (position 502.344 333.738 -50)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -45 526 -50)
      (repeat 20)
      (speed 60))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 132.959 101.286 -50)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 963 380 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1121 334 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 904 380 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 410 275 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 932 398 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1058 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 995 376 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 433 397 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 896 378 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 684 372 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 620 253 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1175 329 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 873 374 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 419 390 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 1001 374 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 937 374 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 820 254 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 601 446 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 607 445 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 24 245 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 840 139 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 471 375 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 438 254 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1150 273 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position -131 247 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 407 343 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 406 254 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_small")
        (modifier "ROT0"))
      (position 202 233 0))
    (entrance 
      (position 178.198 142.524 0)
      (type "generic")
      (direction "right")
      (release-rate 100)
      (owner-id 0))
    (exit 
      (owner-id 0)
      (position 999.51 374.175 0)
      (surface 
        (image "exits/stone")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 596 444 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 1175 250 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 680 370 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 816 251 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 467 373 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 403 340 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 865 371 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 424 340 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 616 250 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 833 136 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position -55 172 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 899 371 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1088 270 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 967 373 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1018 373 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 702 372 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180FLIP"))
      (position -70 274 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0FLIP"))
      (position 8 185 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 138 233 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 168 230 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 234 233 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 228 230 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 74 201 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 71 200 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 136 229 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 297 233 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 342 254 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 291 231 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 359 250 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 430 251 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 68 199 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 659 99 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 652 96 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 862 342 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position -48 308 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 1001 422 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 1099 442 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180FLIP"))
      (position 1048 493 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1174 186 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_large")
        (modifier "ROT0"))
      (position 1111 211 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 1087 324 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1104 207 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1051 337 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1135 271 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 909 342 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 797 222 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 861 222 0))
    (groundpiece 
      (type "solid")
      (surface 
        (image "groundpieces/solid/misc/metalplate_horiz")
        (modifier "ROT0"))
      (position 1159 387 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 806 106 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 870 106 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 625 67 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 689 67 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 590 220 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 654 220 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 656 340 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 720 340 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1043 402 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0FLIP"))
      (position 1152 384 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 67 258 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1112 330 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1081 266 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0FLIP"))
      (position 1170 183 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1089 394 0))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -83 538 100)
      (repeat 21)
      (speed 55))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 132.286 101.898 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
