;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/snow17-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "If too high, your Pingu will die...")
    (description "Teamwork is the way to the exit this time. You don't have enough Floaters "
                 "to reach the exit, so just send a few and let them prepare the path for the "
                 "rest. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 15)
    (number-to-save 8)
    (time -1)
    (difficulty 40)
    (playable 1)
    (comment )
    (music "pingus-8.it")
    (actions 
      (blocker 5)
      (bomber 5)
      (bridger 5)
      (floater 6))
    (levelsize 1700 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/happyclouds")
        (modifier "ROT0"))
      (color 0.2 0 0 0.7)
      (scroll-x 0.3)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 1)
      (keep-aspect 0)
      (position -26.714 -227.286 -150))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 286.668 41.2828 -50)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT0"))
      (position 423 148 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 371 205 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 221 205 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 858 217 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 779 220 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 695 217 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 976 452 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 968 450 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 1040 452 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 1104 452 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1096 450 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1032 450 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1080 450 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 205 149 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 333 149 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 397 149 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 682 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 746 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 810 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 874 158 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 484 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 548 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 612 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 676 361 0))
    (entrance 
      (position 334.357 83.1426 0)
      (type "generic")
      (direction "right")
      (release-rate 150)
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 205 86 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 200 84 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 332 146 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 394 147 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 804 156 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 744 156 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 680 157 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 868 156 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 482 358 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 544 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 668 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 604 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 784 157 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 202 85 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 503 358 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 652 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/snowman")
        (modifier "ROT0"))
      (position 859 50 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/snowman")
        (modifier "ROT0FLIP"))
      (position 703 50 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/xmas-tree")
        (modifier "ROT0"))
      (position 783 61 0))
    (exit 
      (owner-id 0)
      (position 1309.8 410.669 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 740 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 804 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 796 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 732 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 780 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 710 405 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 405 410 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 558 411 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 570 470 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 340 453 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 761 456 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 1118 444 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 1153 407 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 1200 445 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1203 416 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 1291 406 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1231 413 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1254 409 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 1293 408 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 270 505 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 1034 517 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 952 506 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 355 513 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 694 519 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 1232 494 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 1263 540 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 1051 559 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 223 559 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 1259 378 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/rect1")
        (modifier "ROT0"))
      (position 1323 378 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 269 149 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 275 147 0))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 286.688 41.3324 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
