;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/snow22-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Entrance high, Exit low")
    (description "If you don't have enough floaters to bring all the Pingus down to the exit "
                 "- you have to find other ways to guide them down. You should have learned "
                 "all the stuff you need for this level in previous levels, so this shouldn't "
                 "be too much of a problem for you. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 30)
    (number-to-save 20)
    (time -1)
    (difficulty 20)
    (playable 1)
    (comment "deadly distance, doesn't work")
    (music "pingus-5.it")
    (actions 
      (bomber 10)
      (bridger 10)
      (floater 5)
      (miner 5)
      (blocker 10))
    (levelsize 1400 1200))
  (objects 
    (surface-background 
      (surface 
        (image "textures/clouds2")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.3)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 238.5 277.5 -150))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 967 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 1012 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 922 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 1057 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 877 886 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 787 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 967 886 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 832 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 922 931 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 877 841 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 639 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 684 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 594 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 729 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 549 885 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 459 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 639 885 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 504 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock1")
        (modifier "ROT0"))
      (position 594 930 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/diablock2")
        (modifier "ROT0"))
      (position 549 840 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 518 978 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/gpiece1")
        (modifier "ROT0"))
      (position 352 1066 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 648 945 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 816 939 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 618 1075 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 371 1040 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 989 999 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/gpiece1")
        (modifier "ROT0"))
      (position 758 1027 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 904 964 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/gpiece1")
        (modifier "ROT0"))
      (position 1167 1021 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 629 879 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 759 853 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 586 1008 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 676 1011 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 382 1095 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 958 1061 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0"))
      (position 828 1021 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 814 1061 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 1050 1085 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 824 1115 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 600 835 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 441 836 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 976 835 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 816 835 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 750 836 0))
    (exit 
      (owner-id 0)
      (position 1009.5 838.5 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 434 1124 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 471 180 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0"))
      (position 468 242 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 349 176 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece7")
        (modifier "ROT0FLIP"))
      (position 362 244 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 380 178 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 346 176 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 465 177 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 375 432 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 501 432 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 618 434 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 376 431 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 524 431 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 674 431 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 180 547 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 306 547 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece10")
        (modifier "ROT0"))
      (position 423 549 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 181 546 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 329 546 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 479 546 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 562 180 0))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 411.168 40.78 -50)
      (speed -1)
      (parallax 1))
    (entrance 
      (position 458.857 82.64 0)
      (type "generic")
      (direction "right")
      (release-rate 150)
      (owner-id 0))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 411.188 40.83 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
