;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/snow11-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Jump'n Bump... and Bash...")
    (description "It's panic time again. The Pingus will not come out very fast, but since "
                 "they turn around when they hit walls you will soon have some trouble coordinating "
                 "them all. Since you only need to save 5 it should be doable, but if all else "
                 "fails use the pause-mode ('p') to get an overview again. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 10)
    (number-to-save 5)
    (time -1)
    (difficulty 40)
    (playable 1)
    (comment )
    (music "pingus-7.it")
    (actions 
      (basher 5)
      (jumper 50))
    (levelsize 1200 600))
  (objects 
    (surface-background 
      (surface 
        (image "textures/lunartile")
        (modifier "ROT0"))
      (color 0 0 0 0)
      (scroll-x 0.0)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 0)
      (keep-aspect 0)
      (position 0 0 -150))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 143.668 157.283 -50)
      (speed -1)
      (parallax 1))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 688 420 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 448 413 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 499 416 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 574 426 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 927 339 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 416 382 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 863 338 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 981 341 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 80 268 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 228 382 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 174 380 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 110 379 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180"))
      (position 426 349 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 586 269 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece8")
        (modifier "ROT0"))
      (position 385 314 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 650 269 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT180"))
      (position 540 348 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece9")
        (modifier "ROT0FLIP"))
      (position 573 321 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 109 321 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 173 321 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 237 320 0))
    (exit 
      (owner-id 0)
      (position 627.828 269.032 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (entrance 
      (position 190 197 0)
      (type "generic")
      (direction "right")
      (release-rate 250)
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 989 281 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 925 282 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 861 282 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 989 218 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 105 318 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 227 317 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 402 314 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 556 319 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece2")
        (modifier "ROT0"))
      (position 713 319 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/piece3")
        (modifier "ROT0"))
      (position 851 280 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 986 212 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 860 290 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 956 284 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 573 326 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 692 327 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 467 325 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 223 323 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 126 328 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 581 266 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 642 267 0))
    (groundpiece 
      (type "remove")
      (surface 
        (image "groundpieces/remove/misc/column1")
        (modifier "ROT0"))
      (position 803 329 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 405 327 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 531 320 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 645 326 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 629 399 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 653 405 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 968 285 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice1")
        (modifier "ROT0"))
      (position 895 313 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 74 262 0))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 143.688 157.332 100)
      (speed -1)
      (parallax 1))))
;; EOF ;;
