;; generated by xml2sexpr.rb from file 'branches/pingus_0_6/data/levels/tutorial/snow14-grumbel.pingus'
(pingus-level 
  (version 2)
  (head 
    (levelname "Block'a Rock")
    (description "Once again it's time to combine the stuff you have learned in your previous "
                 "levels. Blast your way free and make sure you also keep the rest of the Pingus "
                 "under control. The Blocker action will be helpful. ")
    (author "Ingo Ruhnke <grumbel@gmx.de>")
    (number-of-pingus 35)
    (number-to-save 15)
    (time -1)
    (difficulty 40)
    (playable 1)
    (comment )
    (music "pingus-8.it")
    (actions 
      (blocker 20)
      (bomber 20))
    (levelsize 1200 1000))
  (objects 
    (surface-background 
      (surface 
        (image "textures/happyclouds")
        (modifier "ROT0"))
      (color 0.5 0 0 0.35)
      (scroll-x 0.5)
      (scroll-y 0.0)
      (para-x 0.5)
      (para-y 0.5)
      (stretch-x 0)
      (stretch-y 1)
      (keep-aspect 1)
      (position -35 68.5 -150))
    (hotspot 
      (surface 
        (image "entrances/snow_back")
        (modifier "ROT0"))
      (position 782.475 109.172 -50)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -46 935 -50)
      (repeat 20)
      (speed 55))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 725 644 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 126 535 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 190 535 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 261 754 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 197 753 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 390 754 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 326 754 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 517 756 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 453 755 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 579 755 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 714 870 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 653 871 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 843 870 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 779 870 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 897 872 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 715 415 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 778 416 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 882 307 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT270"))
      (position 443 513 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT270"))
      (position 589 402 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT270"))
      (position 305 302 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT270"))
      (position 384 627 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 446 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 510 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 574 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT270"))
      (position 935 721 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 638 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 702 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 766 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 830 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 894 250 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 277 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 341 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 405 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 469 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 533 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 597 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 661 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 725 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 111 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 175 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 239 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 303 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 367 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 431 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 495 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 559 477 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 288 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 352 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 416 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 480 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 544 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 608 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 672 588 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 736 588 0))
    (entrance 
      (position 828 150 0)
      (type "generic")
      (direction "left")
      (release-rate 120)
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 196 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 260 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 324 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 388 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 452 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 516 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 580 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 644 696 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 650 815 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 714 815 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 778 815 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 842 815 0))
    (exit 
      (owner-id 0)
      (position 835.553 816.912 0)
      (surface 
        (image "exits/ice2")
        (modifier "ROT0"))
      (owner-id 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block1")
        (modifier "ROT0"))
      (position 906 815 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/way")
        (modifier "ROT0"))
      (position 889 719 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 888 711 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 915 711 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 646 812 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 713 813 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 776 813 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 845 813 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 899 812 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 333 360 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 274 359 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 729 586 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 677 585 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 605 585 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 183 472 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 235 473 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 111 471 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 190 695 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 262 695 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 443 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 513 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 565 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 629 247 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 701 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 753 247 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 826 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 888 248 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/block2")
        (modifier "ROT0"))
      (position 789 361 0))
    (groundpiece 
      (type "ground")
      (surface 
        (image "groundpieces/ground/snow/ice2")
        (modifier "ROT0"))
      (position 401 360 0))
    (hotspot 
      (surface 
        (image "entrances/snow_front")
        (modifier "ROT0"))
      (position 783.181 109.638 100)
      (speed -1)
      (parallax 1))
    (liquid 
      (surface 
        (image "liquids/water2")
        (modifier "ROT0"))
      (position -63 944 100)
      (repeat 20)
      (speed 60))))
;; EOF ;;
